package generators

const authSchemaGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
	"{{.FrameworkPath}}/core/auth/authorization"
)

// GeneratedAuthSchema returns the generated authorization schema for the {{.DomainPkg}} domain.
// Use AuthSchema() from authschema.go to customize.
func GeneratedAuthSchema() []authorization.ResourceSchema {
{{- if not .AuthSchemaEntities}}
	return nil
{{- else}}
	return []authorization.ResourceSchema{
{{- range .AuthSchemaEntities}}
		{
			Name: "{{.ResourceType}}",
			Def: authorization.ResourceTypeDef{
				Relations: map[string]authorization.RelationDef{
{{- range .Relations}}
					"{{.Name}}": {AllowedSubjects: []authorization.SubjectTypeRef{
{{- range .AllowedSubjects}}
						{Type: "{{.Type}}"{{if .Relation}}, Relation: "{{.Relation}}"{{end}}},
{{- end}}
					}},
{{- end}}
				},
				Permissions: map[string]authorization.PermissionRule{
{{- range .Permissions}}
					"{{.Name}}": authorization.AnyOf(
{{- range .Checks}}
{{- if .IsDirect}}
						authorization.Direct("{{.Relation}}"),
{{- else}}
						authorization.Through("{{.Relation}}", "{{.Permission}}"),
{{- end}}
{{- end}}
					),
{{- end}}
				},
			},
		},
{{- end}}
	}
{{- end}}
}
`

const authSchemaBootstrapTemplate = `// Package {{.DomainPkg}} authorization schema customization.
// This file is created once and can be customized.

package {{.DomainPkg}}

import (
	"{{.FrameworkPath}}/core/auth/authorization"
)

// AuthSchema returns the authorization schema for the {{.DomainPkg}} domain.
// The generated schema is returned by default.
//
// To customize, modify the returned schema:
//
//	func AuthSchema() []authorization.ResourceSchema {
//		schemas := GeneratedAuthSchema()
//		for i, s := range schemas {
//			if s.Name == "example" {
//				s.Def.Relations["custom_role"] = authorization.RelationDef{
//					AllowedSubjects: []authorization.SubjectTypeRef{
//						{Type: "user"},
//					},
//				}
//				s.Def.Permissions["custom_action"] = authorization.AnyOf(
//					authorization.Direct("custom_role"),
//				)
//				schemas[i] = s
//			}
//		}
//		return schemas
//	}
func AuthSchema() []authorization.ResourceSchema {
	return GeneratedAuthSchema()
}
`
