package generators

// bridgeE2EGeneratedTemplate renders light HTTP e2e tests for one bridged
// entity hosted by a spec-mode database: a self-contained stack (testsqlite →
// spec store → repository → bridge → web handler → httptest.Server), no
// containers. Bodies reuse validCreate<E>Request from the generated
// validation tests (same package, untagged, so it is visible under -tags e2e).
const bridgeE2EGeneratedTemplate = `//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.BridgePackage}}

import (
	"context"
{{- if or .HasRecordState .CreateMaxBodySize}}
	"encoding/json"
{{- end}}
	"net/http/httptest"
{{- if .HasList}}
	"net/url"
{{- end}}
{{- if .CreateMaxBodySize}}
	"strings"
{{- end}}
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"{{.RepoImport}}"
	"{{.StoreImport}}"

	"{{.FrameworkPath}}/infrastructure/ratelimiter"
	"{{.FrameworkPath}}/infrastructure/ratelimiter/memorylimiter"
	"{{.FrameworkPath}}/sdk/logger"
	"{{.FrameworkPath}}/sdk/web"
	"{{.FrameworkPath}}/workshop/testing/testhttp"
	"{{.FrameworkPath}}/workshop/testing/testsqlite"
)

// Ensure imports are used.
var _ = assert.Equal

// setupE2EServer boots the full HTTP stack for {{.EntityName}} against a
// fresh sqlite database: store → repository → bridge → web handler.
// migrateE2EDB is defined in e2e_test.go (bootstrap file).
func setupE2EServer(t *testing.T) *testhttp.Client {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping e2e test")
	}

	ctx := context.Background()
	db := testsqlite.SetupTestSQLite(t, ctx, testsqlite.WithMigrations(migrateE2EDB))

	store, err := {{.StorePkg}}.NewStore(db.Querier(), db.Dialect(), {{.StorePkg}}.TxRunner(db.TxRunner()))
	require.NoError(t, err)
	repo := {{.RepoPkg}}.NewRepository({{.RepoPkg}}.NewCacheStore(store, nil))

	limiter := ratelimiter.New(memorylimiter.New(), ratelimiter.NewDefaultResolver())
	bridge := NewBridge(logger.NewNoop(), repo, limiter)

	handler := web.NewWebHandler()
	bridge.AddHttpRoutes(handler.Group(""))

	srv := httptest.NewServer(handler)
	t.Cleanup(srv.Close)

	return testhttp.New(srv.URL)
}

func TestE2E{{.EntityName}}CreateAndGet(t *testing.T) {
	client := setupE2EServer(t)

	resp := client.Post(t, "{{.CreatePath}}", validCreate{{.EntityName}}Request())
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.{{.PKJSON}}")
	require.NotEmpty(t, id)
{{- if .HasGet}}

	got := client.Get(t, {{.GetPathExpr}})
	got.RequireStatus(t, 200)
	assert.Equal(t, id, got.String(t, "record.{{.PKJSON}}"))

	t.Run("not found", func(t *testing.T) {
		id := "nonexistent-e2e-id"
		client.Get(t, {{.GetPathExpr}}).RequireStatus(t, 404)
	})
{{- end}}
}
{{if .HasList}}
func TestE2E{{.EntityName}}List(t *testing.T) {
	client := setupE2EServer(t)

	client.Post(t, "{{.CreatePath}}", validCreate{{.EntityName}}Request()).RequireStatus(t, 201)
	client.Get(t, "{{.ListPath}}").RequireStatus(t, 200)
}
{{end}}{{if .HasDelete}}
func TestE2E{{.EntityName}}Delete(t *testing.T) {
	client := setupE2EServer(t)

	resp := client.Post(t, "{{.CreatePath}}", validCreate{{.EntityName}}Request())
	resp.RequireStatus(t, 201)
	id := resp.String(t, "record.{{.PKJSON}}")
	require.NotEmpty(t, id)

	client.Delete(t, {{.DeletePathExpr}}).RequireStatus(t, 204)
{{- if .HasGet}}
	client.Get(t, {{.GetPathExpr}}).RequireStatus(t, 404)
{{- end}}
}
{{end}}{{if .HasList}}
func TestE2E{{.EntityName}}SQLInjection(t *testing.T) {
	client := setupE2EServer(t)

	// One known row — an executed OR-1=1 style injection would leak it.
	client.Post(t, "{{.CreatePath}}", validCreate{{.EntityName}}Request()).RequireStatus(t, 201)

	payloads := []string{
		` + "`" + `' OR 1=1 --` + "`" + `,
		` + "`" + `'; DROP TABLE zzz_not_a_table; --` + "`" + `,
		` + "`" + `" OR ""="` + "`" + `,
	}

	// String filter params are parameterized match values: a payload must
	// never error the server and must never match the seeded row.
	stringParams := []string{ {{- range .StringFilterParams}}{{printf "%q" .}}, {{end -}} }
	for _, param := range stringParams {
		for _, payload := range payloads {
			resp := client.Get(t, "{{.ListPath}}?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
			if resp.StatusCode == 200 {
				// Empty result sets marshal as data: null — only a non-empty
				// array is a leak.
				if data, ok := resp.JSON(t)["data"].([]any); ok {
					assert.Empty(t, data,
						"param %q payload %q matched rows — possible injection", param, payload)
				}
			}
		}
	}

	// Non-string filters and order/limit/cursor reject or ignore garbage —
	// never a server error.
	otherParams := []string{ {{- range .OtherProbeParams}}{{printf "%q" .}}, {{end -}} "order", "limit", "cursor"}
	for _, param := range otherParams {
		for _, payload := range payloads {
			resp := client.Get(t, "{{.ListPath}}?"+url.Values{param: []string{payload}}.Encode())
			require.Less(t, resp.StatusCode, 500,
				"param %q payload %q must not cause a server error", param, payload)
		}
	}
}
{{end}}{{if .CreateMaxBodySize}}
func TestE2E{{.EntityName}}OversizedPayload(t *testing.T) {
	client := setupE2EServer(t)

	// A body past the route's max_body_size ({{.CreateMaxBodySize}} bytes) must
	// be rejected with 413, not accepted or 500'd. Pad a valid request with a
	// huge string field the server ignores so only the size trips the limit.
	raw, err := json.Marshal(validCreate{{.EntityName}}Request())
	require.NoError(t, err)
	var body map[string]any
	require.NoError(t, json.Unmarshal(raw, &body))
	body["_padding"] = strings.Repeat("A", {{.CreateMaxBodySize}}+1)

	client.Post(t, "{{.CreatePath}}", body).RequireStatus(t, 413)
}
{{end}}{{if .HasRecordState}}
func TestE2E{{.EntityName}}MassAssignment(t *testing.T) {
	client := setupE2EServer(t)

	// A client smuggling record_state into the create body must not control
	// the stored state — the field is not part of the request model and the
	// lifecycle routes own all transitions (SEC1/P5).
	raw, err := json.Marshal(validCreate{{.EntityName}}Request())
	require.NoError(t, err)
	var body map[string]any
	require.NoError(t, json.Unmarshal(raw, &body))
	body["record_state"] = "zzz-forged-state"

	resp := client.Post(t, "{{.CreatePath}}", body)
	resp.RequireStatus(t, 201)
	assert.NotEqual(t, "zzz-forged-state", resp.String(t, "record.record_state"))
}
{{end}}
`

// bridgeE2EBootstrapTemplate is created once: the migration hook the e2e
// stack uses, mirroring the store packages' integration bootstrap.
const bridgeE2EBootstrapTemplate = `//go:build e2e

// This file is created once by gopernicus and will NOT be overwritten.
// Add custom e2e tests for {{.EntityName}} routes here. The
// setupE2EServer() helper in generated_e2e_test.go provides a fresh stack.

package {{.BridgePackage}}

import (
	"context"
	"os"
	"path/filepath"
	"runtime"

	"{{.FrameworkPath}}/infrastructure/database/sqlite/moderncdb"
)

// migrateE2EDB applies this project's migrations to the e2e test database.
func migrateE2EDB(ctx context.Context, db *moderncdb.DB) error {
	return moderncdb.RunMigrations(ctx, db, os.DirFS(e2eProjectRoot()), "{{.MigrationsDir}}")
}

// e2eProjectRoot walks up from this source file to the directory containing
// go.mod, so the migrations path resolves at any test working directory.
func e2eProjectRoot() string {
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "."
		}
		dir = parent
	}
}
`
