package generators

// bridgeSecurityGeneratedTemplate renders P1 auth-enforcement probes: every
// authenticate:-protected route must reject anonymous and malformed-token
// requests with 401 BEFORE any handler logic runs.
const bridgeSecurityGeneratedTemplate = `//go:build security

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.BridgePackage}}

import (
	"testing"
)

func TestSecurity{{.EntityName}}AuthenticationRequired(t *testing.T) {
	client := setupSecurityServer(t)
	if client == nil {
		t.Skip("setupSecurityServer not wired — see security_test.go to enable enforcement probes")
	}
{{range .Routes}}
	t.Run("{{.Name}} rejects anonymous", func(t *testing.T) {
		{{.Call}}.RequireStatus(t, 401)
	})
{{end}}
	// Same routes with a malformed bearer token — still 401.
	client.SetBearerToken("not-a-real-token")
{{range .Routes}}
	t.Run("{{.Name}} rejects malformed token", func(t *testing.T) {
		{{.Call}}.RequireStatus(t, 401)
	})
{{end}}}
`

const bridgeSecurityBootstrapTemplate = `//go:build security

// This file is created once by gopernicus and will NOT be overwritten.

package {{.BridgePackage}}

import (
	"testing"

	"{{.FrameworkPath}}/workshop/testing/testhttp"
)

// setupSecurityServer boots the app stack WITH authentication enabled and
// returns a client pointed at it. The generated enforcement probes skip
// (loudly) while this returns nil — wire your authenticated test server
// here to activate them.
func setupSecurityServer(t *testing.T) *testhttp.Client {
	t.Helper()
	// TODO: boot your authenticated stack (e.g. via workshop/testing/testserver)
	// and return testhttp.New(server.URL).
	return nil
}
`
