package generators

const bridgeCompositeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.CompositePkg}}

import (
	"log/slog"

{{range .Entities}}
	"{{$.ModulePath}}/bridge/repositories/{{$.CompositePkg}}/{{.BridgePkg}}"
{{- end}}
{{- if .AuthEnabled}}

	"{{.FrameworkPath}}/core/auth/authentication"
	"{{.FrameworkPath}}/core/auth/authorization"
{{- end}}
	"{{.ModulePath}}/core/repositories/{{.DomainName}}"
	"{{.FrameworkPath}}/infrastructure/ratelimiter"
	"{{.FrameworkPath}}/sdk/web"
)

// Bridges contains all bridges for the {{.DomainName}} domain.
type Bridges struct {
	log *slog.Logger
{{- range .Entities}}
	{{.FieldName}} *{{.BridgePkg}}.Bridge
{{- end}}
}

// NewBridges creates all bridges for the {{.DomainName}} domain.
func NewBridges(
	log *slog.Logger,
	repos *{{.DomainName}}.Repositories,
	rateLimiter *ratelimiter.RateLimiter,
{{- if .AuthEnabled}}
	authenticator *authentication.Authenticator,
	authorizer *authorization.Authorizer,
{{- end}}
) *Bridges {
	return &Bridges{
		log: log,
{{- range .Entities}}
		{{.FieldName}}: {{.BridgePkg}}.NewBridge(log, repos.{{.FieldName}}, rateLimiter{{if $.AuthEnabled}}, authenticator, authorizer{{end}}),
{{- end}}
	}
}

// AddHttpRoutes registers all HTTP routes for the {{.DomainName}} domain.
func (b *Bridges) AddHttpRoutes(group *web.RouteGroup) {
{{- range .Entities}}
	b.{{.FieldName}}.AddHttpRoutes(group)
{{- end}}
}

// OpenAPISpec returns aggregated OpenAPI route specs for all {{.DomainName}} bridges.
func (b *Bridges) OpenAPISpec() []web.RouteSpec {
	var specs []web.RouteSpec
{{- range .Entities}}
	specs = append(specs, b.{{.FieldName}}.OpenAPISpec()...)
{{- end}}
	return specs
}
{{- if .AuthEnabled}}

// AuthSchema returns the authorization schema for the {{.DomainName}} domain.
// Delegates to the customizable AuthSchema() function in authschema.go.
func (b *Bridges) AuthSchema() []authorization.ResourceSchema {
	return AuthSchema()
}
{{- end}}
`

// No bootstrap template needed — no more GeneratedBridges/Bridges alias ceremony.
