package generators

// =============================================================================
// Flat bridge generated.go template — ALWAYS REGENERATED
//
// Key differences from embedded (v1) template:
// - Bridge struct has ALL fields directly (no GeneratedBridge embedding)
// - Handler methods on *Bridge (not *GeneratedBridge)
// - Request types use final names (CreateXRequest not GeneratedCreateXRequest)
// - ToRepo maps to repo types directly (no GeneratedCreateX wrapper)
// - NewBridge constructor in generated.go
// - No model.go needed
// =============================================================================

const bridgeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.BridgePackage}}

import (
{{- if .NeedsContextImport}}
	"context"
{{- end}}
{{- if .NeedsJSONImport}}
	"encoding/json"
{{- end}}
{{- if .NeedsFmtImport}}
	"fmt"
{{- end}}
	"net/http"
{{- if .NeedsStrconvImport}}
	"strconv"
{{- end}}
{{- if .NeedsStringsImport}}
	"strings"
{{- end}}
{{- if .NeedsTimeImport}}
	"time"
{{- end}}

{{- if .NeedsBridgeFOPImport}}
	fopb "{{.FrameworkPath}}/bridge/transit/fop"
{{- end}}
	"{{.FrameworkPath}}/bridge/transit/httpmid"
{{- if .NeedsAuthorizationImport}}
	"{{.FrameworkPath}}/core/auth/authorization"
{{- end}}
	"{{.FrameworkPath}}/sdk/errs"
	"{{.FrameworkPath}}/sdk/fop"
{{- if .NeedsValidationImport}}
	"{{.FrameworkPath}}/sdk/validation"
{{- end}}
	"{{.FrameworkPath}}/sdk/web"
	"{{.ModulePath}}/core/repositories/{{if .Module}}{{.Module}}/{{end}}{{.RepoPackage}}"
)

// Ensure imports are used.
{{if .NeedsJSONImport}}var _ = json.RawMessage{}{{end}}
{{if .NeedsFmtImport}}var _ = fmt.Sprintf{{end}}
{{if .NeedsStrconvImport}}var _ = strconv.Atoi{{end}}
{{if .NeedsStringsImport}}var _ = strings.SplitN{{end}}
{{if .NeedsTimeImport}}var _ = time.Time{}{{end}}

// =============================================================================
// Handlers
// =============================================================================
{{range .Routes}}
// {{.HandlerName}} handles {{.Method}} {{.Path}}.
func (b *Bridge) {{.HandlerName}}(w http.ResponseWriter, r *http.Request) {
{{- if eq .Category "list"}}
	qp := parseQueryParams{{.FuncName}}(r)

	page, err := fop.ParsePageStringCursor(qp.Limit, qp.Cursor, {{if .MaxLimit}}{{$.RepoPackage}}.MaxLimit{{.FuncName}}{{else}}0{{end}})
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid pagination: " + err.Error()))
		return
	}

	filter, err := parseFilter{{.FuncName}}(qp)
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid filter: " + err.Error()))
		return
	}

	orderBy, err := parseOrderBy(qp.Order)
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest("invalid order: " + err.Error()))
		return
	}
{{range .PathParams}}
	{{.GoName}} := web.Param(r, "{{.Name}}")
	if {{.GoName}} == "" {
		web.RespondJSONError(w, web.ErrBadRequest("{{.Name}} is required"))
		return
	}
{{end}}
{{- if and .Authorize (eq .Authorize.Pattern "prefilter")}}
	// Prefilter: resolve which specific IDs this subject can read.
{{- if .Authorize.SubjectRef}}
	prefilterResult, err := b.authorizer.LookupResources(r.Context(), authorization.Subject{
		Type: "{{subjectType .Authorize.SubjectRef}}",
		ID:   {{subjectIDExpr .Authorize.SubjectRef}},
	}, "{{.Authorize.Permission}}", "{{$.EntitySingular}}")
{{- else}}
	subject := httpmid.GetSubjectInfo(r.Context())
	prefilterResult, err := b.authorizer.LookupResources(r.Context(), authorization.Subject{
		Type: subject.Type,
		ID:   subject.ID,
	}, "{{.Authorize.Permission}}", "{{$.EntitySingular}}")
{{- end}}
	if err != nil {
		b.log.ErrorContext(r.Context(), "prefilter authorization", "error", err)
		web.RespondJSONError(w, web.ErrInternal("authorization error"))
		return
	}
	if !prefilterResult.Unrestricted {
		filter.AuthorizedIDs = prefilterResult.IDs
	}
{{- end}}

{{- if and .Authorize (eq .Authorize.Pattern "postfilter")}}
	// Postfilter: loop-until-full with batch authorization check.
{{- if .Authorize.SubjectRef}}
	postfilterSubject := authorization.Subject{
		Type: "{{subjectType .Authorize.SubjectRef}}",
		ID:   {{subjectIDExpr .Authorize.SubjectRef}},
	}
{{- else}}
	postfilterSubjectInfo := httpmid.GetSubjectInfo(r.Context())
	postfilterSubject := authorization.Subject{Type: postfilterSubjectInfo.Type, ID: postfilterSubjectInfo.ID}
{{- end}}
	records, pagination, err := fopb.PostfilterLoop(
		r.Context(), b.authorizer, postfilterSubject,
		"{{.Authorize.Permission}}", "{{$.EntitySingular}}",
		func(rec {{$.RepoPackage}}.{{$.EntityName}}) string { return rec.{{$.PKGoName}} },
		func(ctx context.Context, p fop.PageStringCursor) ([]{{$.RepoPackage}}.{{$.EntityName}}, fop.Pagination, error) {
			return b.{{$.EntityNameLower}}Repository.{{.FuncName}}(ctx, filter, {{range .PathParams}}{{.GoName}}, {{end}}orderBy, p)
		},
		page,
	)
{{- else}}
	records, pagination, err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), filter, {{range .PathParams}}{{.GoName}}, {{end}}orderBy, page)
{{- end}}
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondJSONOK(w, fopb.PageResponse[{{$.RepoPackage}}.{{$.EntityName}}]{
		Data:       records,
		Pagination: pagination,
	})

{{- else if eq .Category "create"}}
{{range .PathParams}}
	{{.GoName}} := web.Param(r, "{{.Name}}")
	if {{.GoName}} == "" {
		web.RespondJSONError(w, web.ErrBadRequest("{{.Name}} is required"))
		return
	}
{{end}}
	req, err := web.DecodeJSON[Create{{$.EntityName}}Request](r)
	if err != nil {
		web.RespondJSONError(w, web.ErrValidation(err))
		return
	}

	input, err := req.ToRepo()
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest(err.Error()))
		return
	}
{{range .ParamsToInput}}
	input.{{.GoFieldName}} = {{.GoName}}
{{- end}}

	record, err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), input)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}
{{- if .CreateRels}}

	if err := b.createAuthRelationships(r.Context(), record); err != nil {
		b.log.ErrorContext(r.Context(), "create auth relationships", "error", err)
		web.RespondJSONError(w, web.ErrInternal("create auth relationships"))
		return
	}
{{- end}}

	web.RespondJSONCreated(w, fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{Record: record})

{{- else if or (eq .Category "update") (eq .Category "update_returning")}}
{{range .PathParams}}
	{{.GoName}} := web.Param(r, "{{.Name}}")
	if {{.GoName}} == "" {
		web.RespondJSONError(w, web.ErrBadRequest("{{.Name}} is required"))
		return
	}
{{end}}
	req, err := web.DecodeJSON[Update{{$.EntityName}}Request](r)
	if err != nil {
		web.RespondJSONError(w, web.ErrValidation(err))
		return
	}

	input, err := req.ToRepo()
	if err != nil {
		web.RespondJSONError(w, web.ErrBadRequest(err.Error()))
		return
	}
{{- if eq .Category "update_returning"}}

	record, err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), {{range .PathParams}}{{.GoName}}, {{end}}input)
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondJSONOK(w, fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{Record: record})
{{- else}}

	if err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), {{range .PathParams}}{{.GoName}}, {{end}}input); err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondNoContent(w)
{{- end}}

{{- else if eq .Category "scan_one"}}
{{range .PathParams}}
	{{.GoName}} := web.Param(r, "{{.Name}}")
	if {{.GoName}} == "" {
		web.RespondJSONError(w, web.ErrBadRequest("{{.Name}} is required"))
		return
	}
{{end}}
	record, err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), {{range $i, $p := .PathParams}}{{if $i}}, {{end}}{{$p.GoName}}{{end}})
	if err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}
{{- if and .WithPermissions .Authorize (eq .Authorize.Pattern "check")}}

	subjectInfo := httpmid.GetSubjectInfo(r.Context())
	checkResult, err := b.authorizer.Check(r.Context(), authorization.CheckRequest{
		Subject:    authorization.Subject{Type: subjectInfo.Type, ID: subjectInfo.ID},
		Permission: "{{.Authorize.Permission}}",
		Resource:   authorization.Resource{Type: "{{$.EntitySingular}}", ID: record.{{$.PKGoName}}},
	})
	if err != nil {
		b.log.ErrorContext(r.Context(), "check authorization", "error", err)
		web.RespondJSONError(w, web.ErrInternal("authorization error"))
		return
	}
	if !checkResult.Allowed {
		web.RespondJSONError(w, web.ErrNotFound("{{$.EntityNameLower}} not found"))
		return
	}

	relation := httpmid.ParseRelationFromReason(checkResult.Reason)
	permissions := b.authorizer.GetPermissionsForRelation("{{$.EntitySingular}}", relation)

	web.RespondJSONOK(w, fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{
		Record:       record,
		Relationship: relation,
		Permissions:  permissions,
	})
{{- else}}

	web.RespondJSONOK(w, fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{Record: record})
{{- end}}

{{- else if eq .Category "exec"}}
{{range .PathParams}}
	{{.GoName}} := web.Param(r, "{{.Name}}")
	if {{.GoName}} == "" {
		web.RespondJSONError(w, web.ErrBadRequest("{{.Name}} is required"))
		return
	}
{{end}}
{{- if .DeleteCleanup}}
	if err := b.deleteAuthRelationships(r.Context(), "{{$.EntitySingular}}", {{.DeleteCleanupGoName}}); err != nil {
		b.log.ErrorContext(r.Context(), "delete auth relationships", "error", err)
		web.RespondJSONError(w, web.ErrInternal("delete auth relationships"))
		return
	}

{{- end}}
	if err := b.{{$.EntityNameLower}}Repository.{{.FuncName}}(r.Context(), {{range $i, $p := .PathParams}}{{if $i}}, {{end}}{{$p.GoName}}{{end}}); err != nil {
		if !errs.IsExpected(err) {
			b.log.ErrorContext(r.Context(), "unexpected error", "error", err)
		}
		web.RespondJSONDomainError(w, err)
		return
	}

	web.RespondNoContent(w)
{{- end}}
}
{{end}}
{{- if .HasCreateRels}}
// =============================================================================
// Auth Relationship Creation
// =============================================================================

func (b *Bridge) createAuthRelationships(ctx context.Context, record {{.RepoPackage}}.{{.EntityName}}) error {
	if b.authorizer == nil {
		return nil
	}

	subject := httpmid.GetSubject(ctx)
	parts := strings.SplitN(subject, ":", 2)
	if len(parts) != 2 {
		return fmt.Errorf("invalid subject format: %q", subject)
	}
	subjectType, subjectID := parts[0], parts[1]
	_, _ = subjectType, subjectID

	return b.authorizer.CreateRelationships(ctx, []authorization.CreateRelationship{
{{- range .AllCreateRels}}
		{
			ResourceType: "{{.ResourceType}}",
			ResourceID:   {{.ResourceIDExpr}},
			Relation:     "{{.Relation}}",
{{- if .SubjectFromContext}}
			SubjectType:  subjectType,
			SubjectID:    subjectID,
{{- else}}
			SubjectType:  "{{.SubjectType}}",
			SubjectID:    {{.SubjectIDExpr}},
{{- end}}
		},
{{- end}}
	})
}
{{- end}}
{{- if .HasDeleteRels}}

// =============================================================================
// Auth Relationship Cleanup
// =============================================================================

func (b *Bridge) deleteAuthRelationships(ctx context.Context, resourceType, resourceID string) error {
	if b.authorizer == nil {
		return nil
	}
	return b.authorizer.DeleteResourceRelationships(ctx, resourceType, resourceID)
}
{{- end}}

// =============================================================================
// Query Parsing Helpers
// =============================================================================
{{range .ListQueries}}
// QueryParams{{.FuncName}} holds raw query string values for {{.FuncName}}.
type QueryParams{{.FuncName}} struct {
	Limit      string
	Cursor     string
	Order      string
{{- if .HasSearch}}
	SearchTerm string
{{- end}}
{{- range .FilterFields}}
	{{.GoName}} string
{{- end}}
}

func parseQueryParams{{.FuncName}}(r *http.Request) QueryParams{{.FuncName}} {
	q := r.URL.Query()
	return QueryParams{{.FuncName}}{
		Limit:      q.Get("limit"),
		Cursor:     q.Get("cursor"),
		Order:      q.Get("order"),
{{- if .HasSearch}}
		SearchTerm: q.Get("s"),
{{- end}}
{{- range .FilterFields}}
		{{.GoName}}: q.Get("{{.DBName}}"),
{{- end}}
	}
}

func parseFilter{{.FuncName}}(qp QueryParams{{.FuncName}}) ({{$.RepoPackage}}.Filter{{.FuncName}}, error) {
	var filter {{$.RepoPackage}}.Filter{{.FuncName}}
{{if .HasSearch}}
	if qp.SearchTerm != "" {
		filter.SearchTerm = &qp.SearchTerm
	}
{{end}}
{{- range .FilterFields}}
{{- if .IsString}}
	if qp.{{.GoName}} != "" {
		filter.{{.GoName}} = &qp.{{.GoName}}
	}
{{- else if .IsTime}}
	if qp.{{.GoName}} != "" {
		v, err := time.Parse(time.RFC3339, qp.{{.GoName}})
		if err != nil {
			return filter, fmt.Errorf("invalid {{.DBName}}: %w", err)
		}
		filter.{{.GoName}} = &v
	}
{{- end}}
{{- end}}
	return filter, nil
}
{{end}}
func parseOrderBy(order string) (fop.Order, error) {
	return fop.ParseOrder(
		{{.RepoPackage}}.OrderByFields,
		order,
		fop.NewOrder({{.RepoPackage}}.DefaultOrderBy, {{.RepoPackage}}.DefaultOrderDirection),
	)
}

// =============================================================================
// Request Models
// =============================================================================
{{range .CreateQueries}}
// Create{{$.EntityName}}Request is the HTTP request for creating a {{$.EntityNameLower}}.
type Create{{$.EntityName}}Request struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.DBName}},omitempty"` + "`" + `
{{- end}}
}

// Validate checks all field constraints. Called automatically by web.DecodeJSON.
func (r *Create{{$.EntityName}}Request) Validate() error {
{{- if hasValidation .Fields}}
	var errs web.FieldErrors
{{range .Fields}}
{{- if and .IsRequired .IsString}}
	errs.AddErr("{{.DBName}}", validation.Required("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsEmail (not .IsPointer)}}
	errs.AddErr("{{.DBName}}", validation.Email("{{.DBName}}", r.{{.GoName}}))
{{- else if and .IsEmail .IsPointer}}
	errs.AddErr("{{.DBName}}", validation.EmailPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsURL (not .IsPointer)}}
	errs.AddErr("{{.DBName}}", validation.URL("{{.DBName}}", r.{{.GoName}}))
{{- else if and .IsURL .IsPointer}}
	errs.AddErr("{{.DBName}}", validation.URLPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsSlug (not .IsPointer)}}
	errs.AddErr("{{.DBName}}", validation.Slug("{{.DBName}}", r.{{.GoName}}))
{{- else if and .IsSlug .IsPointer}}
	errs.AddErr("{{.DBName}}", validation.SlugPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsUUID (not .IsPointer)}}
	errs.AddErr("{{.DBName}}", validation.UUID("{{.DBName}}", r.{{.GoName}}))
{{- else if and .IsUUID .IsPointer}}
	errs.AddErr("{{.DBName}}", validation.UUIDPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .MaxLength (not .IsPointer) .IsString}}
	errs.AddErr("{{.DBName}}", validation.MaxLength("{{.DBName}}", r.{{.GoName}}, {{.MaxLength}}))
{{- else if and .MaxLength .IsPointer .IsString}}
	errs.AddErr("{{.DBName}}", validation.MaxLengthPtr("{{.DBName}}", r.{{.GoName}}, {{.MaxLength}}))
{{- end}}
{{- if and .IsEnum (not .IsPointer)}}
	errs.AddErr("{{.DBName}}", validation.OneOf("{{.DBName}}", r.{{.GoName}}, {{enumArgs .EnumValues}}))
{{- else if and .IsEnum .IsPointer}}
	errs.AddErr("{{.DBName}}", validation.OneOfPtr("{{.DBName}}", r.{{.GoName}}, {{enumArgs .EnumValues}}))
{{- end}}
{{- end}}
	return errs.Err()
{{- else}}
	return nil
{{- end}}
}

// ToRepo converts the validated request to a repository input.
func (r Create{{$.EntityName}}Request) ToRepo() ({{$.RepoPackage}}.Create{{$.EntityName}}, error) {
	return {{$.RepoPackage}}.Create{{$.EntityName}}{
{{- range .Fields}}
		{{.GoName}}: r.{{.GoName}},
{{- end}}
	}, nil
}
{{end}}
{{- range .UpdateQueries}}
// Update{{$.EntityName}}Request is the HTTP request for updating a {{$.EntityNameLower}}.
type Update{{$.EntityName}}Request struct {
{{- range .Fields}}
	{{.GoName}} {{.UpdateGoType}} ` + "`" + `json:"{{.DBName}},omitempty"` + "`" + `
{{- end}}
}

// Validate checks all field constraints. Called automatically by web.DecodeJSON.
func (r *Update{{$.EntityName}}Request) Validate() error {
{{- if hasValidation .Fields}}
	var errs web.FieldErrors
{{range .Fields}}
{{- if and .IsEmail .IsString}}
	errs.AddErr("{{.DBName}}", validation.EmailPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsURL .IsString}}
	errs.AddErr("{{.DBName}}", validation.URLPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsSlug .IsString}}
	errs.AddErr("{{.DBName}}", validation.SlugPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .IsUUID .IsString}}
	errs.AddErr("{{.DBName}}", validation.UUIDPtr("{{.DBName}}", r.{{.GoName}}))
{{- end}}
{{- if and .MaxLength .IsString}}
	errs.AddErr("{{.DBName}}", validation.MaxLengthPtr("{{.DBName}}", r.{{.GoName}}, {{.MaxLength}}))
{{- end}}
{{- if .IsEnum}}
	errs.AddErr("{{.DBName}}", validation.OneOfPtr("{{.DBName}}", r.{{.GoName}}, {{enumArgs .EnumValues}}))
{{- end}}
{{- end}}
	return errs.Err()
{{- else}}
	return nil
{{- end}}
}

// ToRepo converts the validated request to a repository input.
func (r Update{{$.EntityName}}Request) ToRepo() ({{$.RepoPackage}}.Update{{$.EntityName}}, error) {
	return {{$.RepoPackage}}.Update{{$.EntityName}}{
{{- range .Fields}}
		{{.GoName}}: r.{{.GoName}},
{{- end}}
	}, nil
}
{{end}}
// =============================================================================
// OpenAPI Spec
// =============================================================================

// =============================================================================
// Generated Route Registration
// =============================================================================

// addGeneratedRoutes registers all generated HTTP routes with middleware.
// Called from AddHttpRoutes in routes.go. Do not edit — regenerated from bridge.yml.
func (b *Bridge) addGeneratedRoutes(group *web.RouteGroup) {
{{- range .Routes}}
	group.{{.Method}}("{{.Path}}", b.{{.HandlerName}},
{{- range .MiddlewareChain}}
{{- if .RateLimit}}
		httpmid.RateLimit(b.rateLimiter, b.log),
{{- else if .Authenticate}}
{{- if eq .Authenticate "user"}}
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors, httpmid.UserOnly()),
{{- else if eq .Authenticate "service_account"}}
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors, httpmid.ServiceAccountOnly()),
{{- else if eq .Authenticate "user_session"}}
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors, httpmid.WithUserSession()),
{{- else}}
		httpmid.Authenticate(b.authenticator, b.log, b.jsonErrors),
{{- end}}
{{- else if .Authorize}}
{{- if eq .Authorize.Pattern "prefilter"}}
		httpmid.AuthorizeType(b.authorizer, b.log, b.jsonErrors, "{{if .Authorize.Entity}}{{.Authorize.Entity}}{{else}}{{$.EntitySingular}}{{end}}", "list"),
{{- else if eq .Authorize.Pattern "postfilter"}}
		httpmid.AuthorizeType(b.authorizer, b.log, b.jsonErrors, "{{if .Authorize.Entity}}{{.Authorize.Entity}}{{else}}{{$.EntitySingular}}{{end}}", "list"),
{{- else}}
		httpmid.AuthorizeParam(b.authorizer, b.log, b.jsonErrors, "{{if .Authorize.Entity}}{{.Authorize.Entity}}{{else}}{{$.EntitySingular}}{{end}}", "{{.Authorize.Permission}}", "{{.Authorize.Param}}"),
{{- end}}
{{- else if .UniqueToID}}
		httpmid.UniqueToID(
			func(ctx context.Context, params map[string]string) (string, error) {
				result, err := b.{{$.EntityNameLower}}Repository.{{.UniqueToID.Resolver}}(ctx, params["{{.UniqueToID.Param}}"])
				if err != nil {
					return "", err
				}
				return result.{{.UniqueToID.IDField}}, nil
			},
			"{{.UniqueToID.TargetParam}}", "{{.UniqueToID.Param}}",
		),
{{- else if .MaxBodySize}}
		httpmid.MaxBodySize({{.MaxBodySize}}),
{{- else if .Raw}}
		{{.Raw}},
{{- end}}
{{- end}}
	)
{{end}}
}

// addGeneratedOpenAPISpec returns OpenAPI route specs for all generated handlers.
func (b *Bridge) addGeneratedOpenAPISpec() []web.RouteSpec {
	return []web.RouteSpec{
{{- range .Routes}}
		{
			Method:        "{{.Method}}",
			Path:          "{{.Path}}",
			Summary:       "{{specSummary .FuncName $.EntityName $.EntityNamePlural}}",
			Tags:          []string{"{{$.EntityNamePlural}}"},
{{- if isPaginated .Category}}
			Paginated:     true,
{{- end}}
{{- if .Authenticated}}
			Authenticated: true, // {{.Authenticated}}
{{- end}}
{{- if eq .Category "create"}}
			RequestBody:   Create{{$.EntityName}}Request{},
			ResponseBody:  fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{},
			StatusCode:    201,
{{- else if or (eq .Category "update") (eq .Category "update_returning")}}
			RequestBody:   Update{{$.EntityName}}Request{},
{{- if eq .Category "update_returning"}}
			ResponseBody:  fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{},
{{- else}}
			StatusCode:    204,
{{- end}}
{{- else if eq .Category "scan_one"}}
			ResponseBody:  fopb.RecordResponse[{{$.RepoPackage}}.{{$.EntityName}}]{},
{{- else if eq .Category "list"}}
			ResponseBody:  fopb.PageResponse[{{$.RepoPackage}}.{{$.EntityName}}]{},
{{- else if eq .Category "exec"}}
			StatusCode:    204,
{{- end}}
		},
{{- end}}
	}
}
`

// =============================================================================
// Flat routes.go template — BOOTSTRAP (created once, customizable)
// =============================================================================

const bridgeRoutesTemplate = `// Package {{.BridgePackage}} provides HTTP routes for {{.EntityName}} operations.
// This file is created once and can be customized.
// Add custom routes, middleware overrides, or additional protocol bindings here.

package {{.BridgePackage}}

import "{{.FrameworkPath}}/sdk/web"

// AddHttpRoutes registers all HTTP routes for {{.EntityName}} operations.
// Generated routes are registered by addGeneratedRoutes (in generated.go).
// Add custom routes below the generated call.
func (b *Bridge) AddHttpRoutes(group *web.RouteGroup) {
	b.addGeneratedRoutes(group)

	// Custom routes:
	// group.GET("/custom-path", b.httpCustomHandler, ...)
}

// OpenAPISpec returns OpenAPI route specs for this bridge.
// Add, remove, or modify entries to control what appears in the API spec.
func (b *Bridge) OpenAPISpec() []web.RouteSpec {
	return b.addGeneratedOpenAPISpec()
}
`

// =============================================================================
// Flat bridge.go template — BOOTSTRAP (created once, customizable)
// =============================================================================

const bridgeBridgeTemplate = `// Package {{.BridgePackage}} provides HTTP bridge for {{.EntityName}} operations.
// This file is created once and can be customized.
// Add custom options, fields, or middleware helpers here.

package {{.BridgePackage}}

import (
	"log/slog"

	"{{.FrameworkPath}}/bridge/transit/httpmid"
	"{{.FrameworkPath}}/core/auth/authentication"
{{- if .AuthEnabled}}
	"{{.FrameworkPath}}/core/auth/authorization"
{{- end}}
	"{{.FrameworkPath}}/infrastructure/ratelimiter"
	"{{.ModulePath}}/core/repositories/{{if .Module}}{{.Module}}/{{end}}{{.RepoPackage}}"
)

// Bridge provides HTTP handlers for {{.EntityName}} operations.
type Bridge struct {
	{{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository
	log           *slog.Logger
	rateLimiter   *ratelimiter.RateLimiter
	authenticator *authentication.Authenticator
{{- if .AuthEnabled}}
	authorizer    *authorization.Authorizer
{{- end}}
	jsonErrors    httpmid.ErrorRenderer
	htmlErrors    httpmid.ErrorRenderer
}

// BridgeOption configures optional Bridge dependencies.
type BridgeOption func(*Bridge)

// WithJSONErrorRenderer overrides the default JSON error renderer.
func WithJSONErrorRenderer(r httpmid.ErrorRenderer) BridgeOption {
	return func(b *Bridge) { b.jsonErrors = r }
}

// WithHTMLErrorRenderer sets the HTML error renderer for server-rendered routes.
func WithHTMLErrorRenderer(r httpmid.ErrorRenderer) BridgeOption {
	return func(b *Bridge) { b.htmlErrors = r }
}

// NewBridge creates a new Bridge with the given dependencies.
func NewBridge(
	log *slog.Logger,
	{{.EntityNameLower}}Repository *{{.RepoPackage}}.Repository,
	rateLimiter *ratelimiter.RateLimiter,
	authenticator *authentication.Authenticator,
{{- if .AuthEnabled}}
	authorizer *authorization.Authorizer,
{{- end}}
	opts ...BridgeOption,
) *Bridge {
	b := &Bridge{
		{{.EntityNameLower}}Repository: {{.EntityNameLower}}Repository,
		log:           log,
		rateLimiter:   rateLimiter,
		authenticator: authenticator,
{{- if .AuthEnabled}}
		authorizer:    authorizer,
{{- end}}
		jsonErrors:    httpmid.JSONErrors{},
	}
	for _, opt := range opts {
		opt(b)
	}
	return b
}
`

// =============================================================================
// Flat http.go template — BOOTSTRAP (created once, for custom handlers)
// =============================================================================

const bridgeHttpTemplate = `// Package {{.BridgePackage}} provides custom HTTP handlers for {{.EntityName}} operations.
// This file is created once and will NOT be overwritten.
//
// Write custom handlers here when you need logic beyond what the generator provides.
// Register them in routes.go alongside the generated routes.
//
// Example:
//
//   func (b *Bridge) httpCustomAction(w http.ResponseWriter, r *http.Request) {
//       // custom logic
//   }

package {{.BridgePackage}}
`

// =============================================================================
// Flat fop.go template — same as v1 but references repo OrderByFields directly
// =============================================================================

const bridgeFopTemplate = `// Package {{.BridgePackage}} provides custom query parsing for {{.EntityName}} operations.
// This file is created once and is never modified by the generator.

package {{.BridgePackage}}
`
