package generators

const bridgeValidationTestTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Unit tests for the generated request-model Validate methods: each negative
// case mutates exactly one field on a known-valid baseline. Pure Go — no
// build tag, no infrastructure.

package {{.BridgePackage}}

import (
{{- if .NeedsStrings}}
	"strings"
{{- end}}
	"testing"
)
{{- if .NeedsTestPtr}}

func testPtr[T any](v T) *T { return &v }
{{- end}}
{{- if .HasCreate}}

func validCreate{{.EntityName}}Request() Create{{.EntityName}}Request {
	return Create{{.EntityName}}Request{
{{- range .CreateValidAssigns}}
		{{.GoName}}: {{.ValueExpr}},
{{- end}}
	}
}

func TestCreate{{.EntityName}}RequestValidate(t *testing.T) {
	t.Run("valid request passes", func(t *testing.T) {
		r := validCreate{{.EntityName}}Request()
		if err := r.Validate(); err != nil {
			t.Fatalf("valid request: unexpected error: %v", err)
		}
	})
{{- range .CreateCases}}
	t.Run("{{.Name}}", func(t *testing.T) {
		r := validCreate{{$.EntityName}}Request()
		r.{{.GoName}} = {{.ValueExpr}}
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
{{- end}}
}
{{- end}}
{{- if .HasUpdate}}

func TestUpdate{{.EntityName}}RequestValidate(t *testing.T) {
	t.Run("empty update passes", func(t *testing.T) {
		r := Update{{.EntityName}}Request{}
		if err := r.Validate(); err != nil {
			t.Fatalf("empty update: unexpected error: %v", err)
		}
	})
{{- range .UpdateCases}}
	t.Run("{{.Name}}", func(t *testing.T) {
		r := Update{{$.EntityName}}Request{}
		r.{{.GoName}} = {{.ValueExpr}}
		if err := r.Validate(); err == nil {
			t.Fatal("want validation error, got nil")
		}
	})
{{- end}}
}
{{- end}}
`
