package generators

const cacheGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.PackageName}}

import (
{{- if .CachedMethods}}
	"context"
{{- if .NeedsFmtImport}}
	"fmt"
{{- end}}
	"time"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
)

// =============================================================================
// Cache Configuration
// =============================================================================

// CacheConfig holds per-method TTL settings.
type CacheConfig struct {
{{- range .CachedMethods}}
	{{.Name}}TTL time.Duration
{{- end}}
	KeyPrefix string
}

// DefaultCacheConfig returns the generated cache defaults.
func DefaultCacheConfig() CacheConfig {
	return CacheConfig{
{{- range .CachedMethods}}
		{{.Name}}TTL: {{.TTLExpr}},
{{- end}}
		KeyPrefix: "{{.KeyPrefix}}",
	}
}

// =============================================================================
// CacheStore
// =============================================================================

// CacheStore wraps a Storer with caching for annotated read methods
// and automatic cache invalidation on writes.
type CacheStore struct {
	Storer
	cache  *cache.Cache
	config CacheConfig
}

// NewCacheStore creates a new CacheStore with default cache configuration.
func NewCacheStore(store Storer, c *cache.Cache) *CacheStore {
	return &CacheStore{
		Storer: store,
		cache:  c,
		config: DefaultCacheConfig(),
	}
}
{{- if .MultiHomed}}

// NewCacheStoreWithKeyPrefix creates a CacheStore whose cache keys use the
// given prefix instead of the default. This entity is hosted by more than
// one database, so each database's generated composite passes a prefix
// qualified with its database name (e.g. "primary:{{.KeyPrefix}}") to keep
// entries from colliding in a shared cache.
func NewCacheStoreWithKeyPrefix(store Storer, c *cache.Cache, keyPrefix string) *CacheStore {
	config := DefaultCacheConfig()
	config.KeyPrefix = keyPrefix
	return &CacheStore{
		Storer: store,
		cache:  c,
		config: config,
	}
}
{{- end}}

{{- if .CachedMethods}}
// =============================================================================
// Cached Read Methods
// =============================================================================
{{range .CachedMethods}}
func (s *CacheStore) {{.Name}}({{.Params}}) ({{.ReturnType}}, error) {
	if s.cache == nil {
		return s.Storer.{{.Name}}({{.CallArgs}})
	}

	key := s.config.KeyPrefix + ":{{.KeySegment}}:" + {{.KeyExpr}}
	result, found, err := cache.GetJSON[{{.ReturnType}}](s.cache, ctx, key)
	if err == nil && found {
		return result, nil
	}

	result, err = s.Storer.{{.Name}}({{.CallArgs}})
	if err != nil {
		return result, err
	}

	if setErr := cache.SetJSON(s.cache, ctx, key, result, s.config.{{.Name}}TTL); setErr != nil {
		// Cache write failure is non-fatal — log but don't fail the request.
		_ = setErr
	}
	return result, nil
}
{{end}}
// =============================================================================
// Write Methods (invalidation)
// =============================================================================
{{range .WriteMethods}}
{{- if .ReturnsEntity}}
func (s *CacheStore) {{.Name}}({{.Params}}) ({{$.EntityName}}, error) {
	result, err := s.Storer.{{.Name}}({{.CallArgs}})
	if err != nil {
		return result, err
	}
	s.invalidateByPK(ctx, {{.PKExpr}})
	return result, nil
}
{{- else}}
func (s *CacheStore) {{.Name}}({{.Params}}) error {
	err := s.Storer.{{.Name}}({{.CallArgs}})
	if err != nil {
		return err
	}
	s.invalidateByPK(ctx, {{.PKExpr}})
	return nil
}
{{- end}}
{{end}}
// =============================================================================
// Invalidation Helpers
// =============================================================================

// invalidateByPK removes all cached entries for a given primary key.
func (s *CacheStore) invalidateByPK(ctx context.Context, pkValue string) {
	if s.cache == nil {
		return
	}
	pattern := s.config.KeyPrefix + ":*:" + pkValue
	_ = s.cache.DeletePattern(ctx, pattern)
}

// InvalidateByID is a public helper for manual cache invalidation.
func (s *CacheStore) InvalidateByID(ctx context.Context, id string) {
	s.invalidateByPK(ctx, id)
}

// InvalidateAll removes all cached entries for this entity.
func (s *CacheStore) InvalidateAll(ctx context.Context) {
	if s.cache == nil {
		return
	}
	_ = s.cache.DeletePattern(ctx, s.config.KeyPrefix+":*")
}
{{- end}}
`

const cacheBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// CacheStore is defined in generated_cache.go. Add custom cache methods here.
//
// Example — custom invalidation on a domain event:
//
//	func (s *CacheStore) InvalidateForTenant(ctx context.Context, tenantID string) {
//		_ = s.cache.DeletePattern(ctx, s.config.KeyPrefix+":*")
//	}

package {{.PackageName}}
`
