package generators

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func specCompositeData() CompositeTemplateData {
	return CompositeTemplateData{
		DomainPkg:     "auth",
		ModulePath:    "github.com/example/app",
		FrameworkPath: gopernicusFrameworkPath,
		DomainPath:    "core/repositories/auth",
		Entities: []CompositeEntity{
			{FieldName: "Credential", RepoPkg: "credentials", StorePkg: "credentialsstore", EntityName: "Credential"},
			{FieldName: "User", RepoPkg: "users", StorePkg: "usersstore", EntityName: "User"},
		},
		SpecMode: true,
	}
}

// TestCompositeSpecRender pins the spec-mode composite: dialect-neutral
// crud.Querier/crud.Dialect wiring, a shared TxRunner converted per entity
// store, and an error-returning constructor — with no pgx coupling.
func TestCompositeSpecRender(t *testing.T) {
	data := specCompositeData()
	domainDir := t.TempDir()

	if err := GenerateComposite(data, domainDir, Options{}); err != nil {
		t.Fatalf("GenerateComposite: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
	if err != nil {
		t.Fatalf("read generated_composite.go: %v", err)
	}
	generated := string(raw)

	wantFragments := []string{
		"// Code generated by gopernicus. DO NOT EDIT.",
		"package auth",

		// Imports: entity repos + spec stores from ModulePath, infra from FrameworkPath.
		`"github.com/example/app/core/repositories/auth/users"`,
		`"github.com/example/app/core/repositories/auth/users/usersstore"`,
		`"github.com/gopernicus/gopernicus/infrastructure/cache"`,
		`"github.com/gopernicus/gopernicus/infrastructure/database/crud"`,
		`gopevents "github.com/gopernicus/gopernicus/infrastructure/events"`,

		// Shared TxRunner, converted to each entity store's TxRunner.
		"type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error",

		// Constructor: crud.Querier/Dialect params, error return.
		"func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus gopevents.Bus) (*Repositories, error)",

		// Spec store construction with error handling per entity.
		"usersStore, err := usersstore.NewStore(q, d, usersstore.TxRunner(inTx))",
		`return nil, fmt.Errorf("users store: %w", err)`,
		"credentialsStore, err := credentialsstore.NewStore(q, d, credentialsstore.TxRunner(inTx))",
		`return nil, fmt.Errorf("credentials store: %w", err)`,

		// Repository wiring through the cache wrapper and event bus.
		"users.NewCacheStore(usersStore, c)",
		"users.WithEventBus(bus)",
		"credentials.NewCacheStore(credentialsStore, c)",
	}
	for _, want := range wantFragments {
		if !strings.Contains(generated, want) {
			t.Errorf("generated_composite.go missing fragment:\n%s", want)
		}
	}

	for _, banned := range []string{"pgxdb", "pgx.", "userspgx"} {
		if strings.Contains(generated, banned) {
			t.Errorf("spec composite must not contain %q", banned)
		}
	}

	if t.Failed() {
		t.Logf("generated_composite.go:\n%s", generated)
	}
}

// singleDBPgxGolden pins the byte-exact single-database pgx composite output:
// a domain hosted by exactly one database must keep producing exactly this
// file even though the templates also serve multi-database rendering.
const singleDBPgxGolden = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package events

import (
	"log/slog"

	"github.com/example/app/core/repositories/events/eventoutbox"
	"github.com/example/app/core/repositories/events/eventoutbox/eventoutboxpgx"

	"github.com/gopernicus/gopernicus/infrastructure/cache"
	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
	gopevents "github.com/gopernicus/gopernicus/infrastructure/events"
)

// Repositories contains all repositories for the events domain.
type Repositories struct {
	EventOutbox *eventoutbox.Repository
}

// NewRepositories creates all repositories for the events domain.
// db accepts *pgxdb.Pool for normal operations or a pgx.Tx for transactional workflows.
// If c is nil, cache is a passthrough (no caching, falls through to database).
func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus gopevents.Bus) *Repositories {
	return &Repositories{
		EventOutbox: eventoutbox.NewRepository(
			eventoutbox.NewCacheStore(eventoutboxpgx.NewStore(log, db), c),
			eventoutbox.WithEventBus(bus),
		),
	}
}
`

// singleDBSpecGolden is the spec-mode equivalent of singleDBPgxGolden.
const singleDBSpecGolden = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package events

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/example/app/core/repositories/events/eventoutbox"
	"github.com/example/app/core/repositories/events/eventoutbox/eventoutboxstore"

	"github.com/gopernicus/gopernicus/infrastructure/cache"
	"github.com/gopernicus/gopernicus/infrastructure/database/crud"
	gopevents "github.com/gopernicus/gopernicus/infrastructure/events"
)

// TxRunner executes fn inside a transaction, providing a tx-scoped querier.
// Wiring supplies it per driver (e.g. a pgx or database/sql transaction
// wrapped in the matching crud querier adapter); NewRepositories converts it
// to each entity store's TxRunner.
type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error

// Repositories contains all repositories for the events domain.
type Repositories struct {
	EventOutbox *eventoutbox.Repository
}

// NewRepositories creates all repositories for the events domain over
// any crud-supported database: q and d come from the chosen driver adapter
// (e.g. crud/pgxq or crud/sqliteq) and inTx runs a function inside a
// transaction on the same connection.
// If c is nil, cache is a passthrough (no caching, falls through to database).
func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus gopevents.Bus) (*Repositories, error) {
	eventoutboxStore, err := eventoutboxstore.NewStore(q, d, eventoutboxstore.TxRunner(inTx))
	if err != nil {
		return nil, fmt.Errorf("eventoutbox store: %w", err)
	}

	return &Repositories{
		EventOutbox: eventoutbox.NewRepository(
			eventoutbox.NewCacheStore(eventoutboxStore, c),
			eventoutbox.WithEventBus(bus),
		),
	}, nil
}
`

func singleEventOutboxData(storePkg string, specMode bool) CompositeTemplateData {
	return CompositeTemplateData{
		DomainPkg:     "events",
		ModulePath:    "github.com/example/app",
		FrameworkPath: gopernicusFrameworkPath,
		DomainPath:    "core/repositories/events",
		Entities: []CompositeEntity{
			{FieldName: "EventOutbox", RepoPkg: "eventoutbox", StorePkg: storePkg, EntityName: "EventOutbox"},
		},
		SpecMode: specMode,
	}
}

// TestCompositeSingleDatabase_ByteCompat verifies that a domain hosted by
// exactly one database produces byte-identical output to the pre-multi-db
// templates, for both store modes.
func TestCompositeSingleDatabase_ByteCompat(t *testing.T) {
	tests := []struct {
		name   string
		data   CompositeTemplateData
		golden string
	}{
		{"pgx", singleEventOutboxData("eventoutboxpgx", false), singleDBPgxGolden},
		{"spec", singleEventOutboxData("eventoutboxstore", true), singleDBSpecGolden},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			domainDir := t.TempDir()
			if err := GenerateDomainComposites(domainDir, []DBComposite{{DBName: "primary", Data: tc.data}}, Options{}); err != nil {
				t.Fatalf("GenerateDomainComposites: %v", err)
			}
			raw, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
			if err != nil {
				t.Fatalf("read generated_composite.go: %v", err)
			}
			if string(raw) != tc.golden {
				t.Errorf("single-database composite is not byte-compatible\n--- got ---\n%s\n--- want ---\n%s", raw, tc.golden)
			}
		})
	}
}

// TestGenerateDomainComposites_MultiDatabase covers a domain hosted by a
// pgx-mode and a spec-mode database: shared types in generated_composite.go,
// one constructor file per database in the right mode, db-qualified cache
// prefixes, and stale per-db file cleanup.
func TestGenerateDomainComposites_MultiDatabase(t *testing.T) {
	domainDir := t.TempDir()

	pgxData := singleEventOutboxData("eventoutboxpgx", false)
	pgxData.Entities[0].CacheKeyPrefix = "primary:events:event_outbox"
	specData := singleEventOutboxData("eventoutboxstore", true)
	specData.Entities[0].CacheKeyPrefix = "otherdb:events:event_outbox"

	// Pre-seed a stale per-db composite that this run does not produce.
	stale := filepath.Join(domainDir, "generated_composite_olddb.go")
	if err := os.WriteFile(stale, []byte("// Code generated by gopernicus. DO NOT EDIT.\npackage events\n"), 0644); err != nil {
		t.Fatalf("seed stale file: %v", err)
	}

	composites := []DBComposite{
		{DBName: "primary", Data: pgxData},
		{DBName: "otherdb", Data: specData},
	}
	if err := GenerateDomainComposites(domainDir, composites, Options{}); err != nil {
		t.Fatalf("GenerateDomainComposites: %v", err)
	}

	shared, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
	if err != nil {
		t.Fatalf("read shared types file: %v", err)
	}
	for _, want := range []string{
		"type Repositories struct {",
		"EventOutbox *eventoutbox.Repository",
		"type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error",
		"primary, otherdb",
	} {
		if !strings.Contains(string(shared), want) {
			t.Errorf("generated_composite.go missing fragment %q\n--- output ---\n%s", want, shared)
		}
	}
	if strings.Contains(string(shared), "func NewRepositories") {
		t.Errorf("shared types file must not declare constructors\n--- output ---\n%s", shared)
	}

	pgxFile, err := os.ReadFile(filepath.Join(domainDir, "generated_composite_primary.go"))
	if err != nil {
		t.Fatalf("read generated_composite_primary.go: %v", err)
	}
	for _, want := range []string{
		"func NewRepositoriesPrimary(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus gopevents.Bus) *Repositories {",
		`eventoutbox.NewCacheStoreWithKeyPrefix(eventoutboxpgx.NewStore(log, db), c, "primary:events:event_outbox")`,
	} {
		if !strings.Contains(string(pgxFile), want) {
			t.Errorf("generated_composite_primary.go missing fragment %q\n--- output ---\n%s", want, pgxFile)
		}
	}
	for _, banned := range []string{"type Repositories struct", "type TxRunner"} {
		if strings.Contains(string(pgxFile), banned) {
			t.Errorf("per-db composite must not contain %q", banned)
		}
	}

	specFile, err := os.ReadFile(filepath.Join(domainDir, "generated_composite_otherdb.go"))
	if err != nil {
		t.Fatalf("read generated_composite_otherdb.go: %v", err)
	}
	for _, want := range []string{
		"func NewRepositoriesOtherdb(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus gopevents.Bus) (*Repositories, error) {",
		`eventoutbox.NewCacheStoreWithKeyPrefix(eventoutboxStore, c, "otherdb:events:event_outbox")`,
	} {
		if !strings.Contains(string(specFile), want) {
			t.Errorf("generated_composite_otherdb.go missing fragment %q\n--- output ---\n%s", want, specFile)
		}
	}
	for _, banned := range []string{"type Repositories struct", "type TxRunner", `"context"`} {
		if strings.Contains(string(specFile), banned) {
			t.Errorf("per-db spec composite must not contain %q", banned)
		}
	}

	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale per-db composite %s was not removed", stale)
	}
}

// TestCompositePgxRender_Unchanged pins that pgx mode still renders the
// pgx-coupled composite (the spec variant must not leak into the default).
func TestCompositePgxRender_Unchanged(t *testing.T) {
	data := specCompositeData()
	data.SpecMode = false
	for i := range data.Entities {
		data.Entities[i].StorePkg = StorePackage(data.Entities[i].RepoPkg, "pgx")
	}
	domainDir := t.TempDir()

	if err := GenerateComposite(data, domainDir, Options{}); err != nil {
		t.Fatalf("GenerateComposite: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
	if err != nil {
		t.Fatalf("read generated_composite.go: %v", err)
	}
	generated := string(raw)

	if !strings.Contains(generated, "func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus gopevents.Bus) *Repositories") {
		t.Errorf("pgx composite signature changed\n--- output ---\n%s", generated)
	}
	for _, banned := range []string{"crud.Querier", "crud.Dialect", "TxRunner"} {
		if strings.Contains(generated, banned) {
			t.Errorf("pgx composite must not contain %q", banned)
		}
	}
}
