package generators

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func specCompositeData() CompositeTemplateData {
	return CompositeTemplateData{
		DomainPkg:     "auth",
		ModulePath:    "github.com/example/app",
		FrameworkPath: gopernicusFrameworkPath,
		DomainPath:    "core/repositories/auth",
		Entities: []CompositeEntity{
			{FieldName: "Credential", RepoPkg: "credentials", StorePkg: "credentialsstore", EntityName: "Credential", HasEvents: true},
			{FieldName: "User", RepoPkg: "users", StorePkg: "usersstore", EntityName: "User", HasEvents: true},
		},
		HasEvents: true,
		SpecMode:  true,
	}
}

// TestCompositeSpecRender pins the spec-mode composite: dialect-neutral
// crud.Querier/crud.Dialect wiring, a shared TxRunner converted per entity
// store, and an error-returning constructor — with no pgx coupling.
func TestCompositeSpecRender(t *testing.T) {
	data := specCompositeData()
	domainDir := t.TempDir()

	if err := GenerateComposite(data, domainDir, Options{}); err != nil {
		t.Fatalf("GenerateComposite: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
	if err != nil {
		t.Fatalf("read generated_composite.go: %v", err)
	}
	generated := string(raw)

	wantFragments := []string{
		"// Code generated by gopernicus. DO NOT EDIT.",
		"package auth",

		// Imports: entity repos + spec stores from ModulePath, infra from FrameworkPath.
		`"github.com/example/app/core/repositories/auth/users"`,
		`"github.com/example/app/core/repositories/auth/users/usersstore"`,
		`"github.com/gopernicus/gopernicus/infrastructure/cache"`,
		`"github.com/gopernicus/gopernicus/infrastructure/database/crud"`,
		`"github.com/gopernicus/gopernicus/infrastructure/events"`,

		// Shared TxRunner, converted to each entity store's TxRunner.
		"type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error",

		// Constructor: crud.Querier/Dialect params, error return.
		"func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus events.Bus) (*Repositories, error)",

		// Spec store construction with error handling per entity.
		"usersStore, err := usersstore.NewStore(q, d, usersstore.TxRunner(inTx))",
		`return nil, fmt.Errorf("users store: %w", err)`,
		"credentialsStore, err := credentialsstore.NewStore(q, d, credentialsstore.TxRunner(inTx))",
		`return nil, fmt.Errorf("credentials store: %w", err)`,

		// Repository wiring through the cache wrapper and event bus.
		"users.NewCacheStore(usersStore, c)",
		"users.WithEventBus(bus)",
		"credentials.NewCacheStore(credentialsStore, c)",
	}
	for _, want := range wantFragments {
		if !strings.Contains(generated, want) {
			t.Errorf("generated_composite.go missing fragment:\n%s", want)
		}
	}

	for _, banned := range []string{"pgxdb", "pgx.", "userspgx"} {
		if strings.Contains(generated, banned) {
			t.Errorf("spec composite must not contain %q", banned)
		}
	}

	if t.Failed() {
		t.Logf("generated_composite.go:\n%s", generated)
	}
}

// TestCompositeSpecRender_NoEvents covers the events-free constructor variant.
func TestCompositeSpecRender_NoEvents(t *testing.T) {
	data := specCompositeData()
	data.HasEvents = false
	for i := range data.Entities {
		data.Entities[i].HasEvents = false
	}

	out, err := renderCompositeTemplate(compositeSpecGeneratedTemplate, data)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	formatted, err := format.Source(out)
	if err != nil {
		t.Fatalf("go/format: %v\n--- output ---\n%s", err, out)
	}
	generated := string(formatted)

	if !strings.Contains(generated,
		"func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache) (*Repositories, error)") {
		t.Errorf("missing events-free constructor signature\n--- output ---\n%s", generated)
	}
	for _, banned := range []string{"events.Bus", "WithEventBus"} {
		if strings.Contains(generated, banned) {
			t.Errorf("events-free composite must not contain %q", banned)
		}
	}
}

// TestCompositePgxRender_Unchanged pins that pgx mode still renders the
// pgx-coupled composite (the spec variant must not leak into the default).
func TestCompositePgxRender_Unchanged(t *testing.T) {
	data := specCompositeData()
	data.SpecMode = false
	for i := range data.Entities {
		data.Entities[i].StorePkg = StorePackage(data.Entities[i].RepoPkg, "pgx")
	}
	domainDir := t.TempDir()

	if err := GenerateComposite(data, domainDir, Options{}); err != nil {
		t.Fatalf("GenerateComposite: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(domainDir, "generated_composite.go"))
	if err != nil {
		t.Fatalf("read generated_composite.go: %v", err)
	}
	generated := string(raw)

	if !strings.Contains(generated, "func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus events.Bus) *Repositories") {
		t.Errorf("pgx composite signature changed\n--- output ---\n%s", generated)
	}
	for _, banned := range []string{"crud.Querier", "crud.Dialect", "TxRunner"} {
		if strings.Contains(generated, banned) {
			t.Errorf("pgx composite must not contain %q", banned)
		}
	}
}
