package generators

const compositeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
	"log/slog"
{{range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}/{{.StorePkg}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
	"{{.FrameworkPath}}/infrastructure/database/postgres/pgxdb"
{{- if .HasEvents}}
	"{{.FrameworkPath}}/infrastructure/events"
{{- end}}
)

// Repositories contains all repositories for the {{.DomainPkg}} domain.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}

// NewRepositories creates all repositories for the {{.DomainPkg}} domain.
// db accepts *pgxdb.Pool for normal operations or a pgx.Tx for transactional workflows.
// If c is nil, cache is a passthrough (no caching, falls through to database).
{{- if .HasEvents}}
func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus events.Bus) *Repositories {
{{- else}}
func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache) *Repositories {
{{- end}}
	return &Repositories{
{{- range .Entities}}
{{- if .HasEvents}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.StorePkg}}.NewStore(log, db), c),
			{{.RepoPkg}}.WithEventBus(bus),
		),
{{- else}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.StorePkg}}.NewStore(log, db), c),
		),
{{- end}}
{{- end}}
	}
}
`

// No bootstrap template needed — no more GeneratedRepositories/Repositories alias ceremony.
