package generators

const compositeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
	"log/slog"
{{range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}/{{.StorePkg}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
	"{{.FrameworkPath}}/infrastructure/database/postgres/pgxdb"
	gopevents "{{.FrameworkPath}}/infrastructure/events"
)
{{if not .OmitTypes}}
// Repositories contains all repositories for the {{.DomainPkg}} domain.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}
{{end}}
{{- if .ConstructorSuffix}}
// NewRepositories{{.ConstructorSuffix}} creates the {{.DomainPkg}} repositories hosted by the
// "{{.DBName}}" database, populating only the entities it declares.
{{- else}}
// NewRepositories creates all repositories for the {{.DomainPkg}} domain.
{{- end}}
// db accepts *pgxdb.Pool for normal operations or a pgx.Tx for transactional workflows.
// If c is nil, cache is a passthrough (no caching, falls through to database).
func NewRepositories{{.ConstructorSuffix}}(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus gopevents.Bus) *Repositories {
	return &Repositories{
{{- range .Entities}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.{{if .CacheKeyPrefix}}NewCacheStoreWithKeyPrefix({{.StorePkg}}.NewStore(log, db), c, "{{.CacheKeyPrefix}}"){{else}}NewCacheStore({{.StorePkg}}.NewStore(log, db), c){{end}},
			{{.RepoPkg}}.WithEventBus(bus),
		),
{{- end}}
	}
}
`

// compositeSpecGeneratedTemplate is the spec-store-mode variant: instead of
// hard-wiring pgx (pgxdb.Querier + <entity>pgx.NewStore), it wires the
// dialect-neutral <entity>store packages over a crud.Querier + crud.Dialect
// pair and a transaction runner, so the same composite serves any
// crud-supported database.
const compositeSpecGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
{{- if not .OmitTypes}}
	"context"
{{- end}}
	"fmt"
	"log/slog"
{{range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}/{{.StorePkg}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
	"{{.FrameworkPath}}/infrastructure/database/crud"
	gopevents "{{.FrameworkPath}}/infrastructure/events"
)
{{if not .OmitTypes}}
// TxRunner executes fn inside a transaction, providing a tx-scoped querier.
// Wiring supplies it per driver (e.g. a pgx or database/sql transaction
// wrapped in the matching crud querier adapter); NewRepositories converts it
// to each entity store's TxRunner.
type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error

// Repositories contains all repositories for the {{.DomainPkg}} domain.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}
{{end}}
{{- if .ConstructorSuffix}}
// NewRepositories{{.ConstructorSuffix}} creates the {{.DomainPkg}} repositories hosted by the
// "{{.DBName}}" database, populating only the entities it declares: q and d
// come from the chosen driver adapter (e.g. crud/pgxq or crud/sqliteq) and
// inTx runs a function inside a transaction on the same connection.
{{- else}}
// NewRepositories creates all repositories for the {{.DomainPkg}} domain over
// any crud-supported database: q and d come from the chosen driver adapter
// (e.g. crud/pgxq or crud/sqliteq) and inTx runs a function inside a
// transaction on the same connection.
{{- end}}
// If c is nil, cache is a passthrough (no caching, falls through to database).
func NewRepositories{{.ConstructorSuffix}}(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus gopevents.Bus) (*Repositories, error) {
{{- range .Entities}}
	{{.RepoPkg}}Store, err := {{.StorePkg}}.NewStore(q, d, {{.StorePkg}}.TxRunner(inTx))
	if err != nil {
		return nil, fmt.Errorf("{{.RepoPkg}} store: %w", err)
	}
{{- end}}

	return &Repositories{
{{- range .Entities}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.{{if .CacheKeyPrefix}}NewCacheStoreWithKeyPrefix({{.RepoPkg}}Store, c, "{{.CacheKeyPrefix}}"){{else}}NewCacheStore({{.RepoPkg}}Store, c){{end}},
			{{.RepoPkg}}.WithEventBus(bus),
		),
{{- end}}
	}, nil
}
`

// compositeSharedTypesTemplate renders generated_composite.go for a domain
// hosted by more than one database: the shared Repositories struct (plus the
// TxRunner type when any hosting database uses the spec store mode). The
// per-database constructors live in generated_composite_<db>.go files.
const compositeSharedTypesTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
{{- if .NeedsTxRunner}}
	"context"
{{- end}}
{{- range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
{{- end}}
{{- if .NeedsTxRunner}}
	"{{.FrameworkPath}}/infrastructure/database/crud"
{{- end}}
)

// Repositories contains all repositories for the {{.DomainPkg}} domain. The
// domain is hosted by more than one database ({{.DBList}}); each
// NewRepositories<Db> constructor (one generated_composite_<db>.go per
// database) populates the entities its database declares and leaves the
// rest nil.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}
{{- if .NeedsTxRunner}}

// TxRunner executes fn inside a transaction, providing a tx-scoped querier.
// Wiring supplies it per driver (e.g. a pgx or database/sql transaction
// wrapped in the matching crud querier adapter); the spec-mode constructors
// convert it to each entity store's TxRunner.
type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error
{{- end}}
`
