package generators

const compositeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
	"log/slog"
{{range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}/{{.StorePkg}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
	"{{.FrameworkPath}}/infrastructure/database/postgres/pgxdb"
{{- if .HasEvents}}
	"{{.FrameworkPath}}/infrastructure/events"
{{- end}}
)

// Repositories contains all repositories for the {{.DomainPkg}} domain.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}

// NewRepositories creates all repositories for the {{.DomainPkg}} domain.
// db accepts *pgxdb.Pool for normal operations or a pgx.Tx for transactional workflows.
// If c is nil, cache is a passthrough (no caching, falls through to database).
{{- if .HasEvents}}
func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache, bus events.Bus) *Repositories {
{{- else}}
func NewRepositories(log *slog.Logger, db pgxdb.Querier, c *cache.Cache) *Repositories {
{{- end}}
	return &Repositories{
{{- range .Entities}}
{{- if .HasEvents}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.StorePkg}}.NewStore(log, db), c),
			{{.RepoPkg}}.WithEventBus(bus),
		),
{{- else}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.StorePkg}}.NewStore(log, db), c),
		),
{{- end}}
{{- end}}
	}
}
`

// compositeSpecGeneratedTemplate is the spec-store-mode variant: instead of
// hard-wiring pgx (pgxdb.Querier + <entity>pgx.NewStore), it wires the
// dialect-neutral <entity>store packages over a crud.Querier + crud.Dialect
// pair and a transaction runner, so the same composite serves any
// crud-supported database.
const compositeSpecGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.DomainPkg}}

import (
	"context"
	"fmt"
	"log/slog"
{{range .Entities}}
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}"
	"{{$.ModulePath}}/{{$.DomainPath}}/{{.RepoPkg}}/{{.StorePkg}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cache"
	"{{.FrameworkPath}}/infrastructure/database/crud"
{{- if .HasEvents}}
	"{{.FrameworkPath}}/infrastructure/events"
{{- end}}
)

// TxRunner executes fn inside a transaction, providing a tx-scoped querier.
// Wiring supplies it per driver (e.g. a pgx or database/sql transaction
// wrapped in the matching crud querier adapter); NewRepositories converts it
// to each entity store's TxRunner.
type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error

// Repositories contains all repositories for the {{.DomainPkg}} domain.
type Repositories struct {
{{- range .Entities}}
	{{.FieldName}} *{{.RepoPkg}}.Repository
{{- end}}
}

// NewRepositories creates all repositories for the {{.DomainPkg}} domain over
// any crud-supported database: q and d come from the chosen driver adapter
// (e.g. crud/pgxq or crud/sqliteq) and inTx runs a function inside a
// transaction on the same connection.
// If c is nil, cache is a passthrough (no caching, falls through to database).
{{- if .HasEvents}}
func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache, bus events.Bus) (*Repositories, error) {
{{- else}}
func NewRepositories(log *slog.Logger, q crud.Querier, d crud.Dialect, inTx TxRunner, c *cache.Cache) (*Repositories, error) {
{{- end}}
{{- range .Entities}}
	{{.RepoPkg}}Store, err := {{.StorePkg}}.NewStore(q, d, {{.StorePkg}}.TxRunner(inTx))
	if err != nil {
		return nil, fmt.Errorf("{{.RepoPkg}} store: %w", err)
	}
{{- end}}

	return &Repositories{
{{- range .Entities}}
{{- if .HasEvents}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.RepoPkg}}Store, c),
			{{.RepoPkg}}.WithEventBus(bus),
		),
{{- else}}
		{{.FieldName}}: {{.RepoPkg}}.NewRepository(
			{{.RepoPkg}}.NewCacheStore({{.RepoPkg}}Store, c),
		),
{{- end}}
{{- end}}
	}, nil
}
`

// No bootstrap template needed — no more GeneratedRepositories/Repositories alias ceremony.
