package generators

const e2eTestGeneratedTemplate = `//go:build e2e

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"{{.FixtureImport}}"
	"{{.FrameworkPath}}/infrastructure/cryptids"
	"{{.FrameworkPath}}/workshop/testing/testhttp"
)

// Ensure imports are used.
var (
	_ = assert.Equal
	_ = require.NoError
	_ = cryptids.GenerateID
)
{{if .HasCreate}}
func TestGenerated{{.EntityName}}_Create(t *testing.T) {
	_, _, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())
	// TODO: Set authentication if routes require it.
	// client.SetBearerToken(token)

	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID

	body := map[string]any{
		{{- range .CreateFields}}{{if and .TestDefault (not .IsFK)}}
		"{{.JSONName}}": {{.TestDefault}},
		{{- end}}{{end}}
	}

	resp := client.Post(t, "{{.CreatePath}}", body)
	resp.RequireStatus(t, 201)
	{{- if .HasGet}}

	createdID := resp.String(t, "{{.PKColumn}}")
	assert.NotEmpty(t, createdID)

	// Verify via GET.
	getResp := client.Get(t, {{testPath .GetPath "createdID" ""}})
	getResp.RequireStatus(t, 200)
	assert.Equal(t, createdID, getResp.String(t, "{{.PKColumn}}"))
	{{- end}}
}
{{end}}{{if .HasGet}}
func TestGenerated{{.EntityName}}_Get(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		resp := client.Get(t, {{testPath .GetPath "created." .PKGoName}})
		resp.RequireStatus(t, 200)
		assert.Equal(t, created.{{.PKGoName}}, resp.String(t, "{{.PKColumn}}"))
	})

	t.Run("not found", func(t *testing.T) {
		resp := client.Get(t, {{testPath .GetPath "\"nonexistent-id\"" ""}})
		resp.RequireStatus(t, 404)
	})
}
{{end}}{{if .HasList}}
func TestGenerated{{.EntityName}}_List(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	for i := 0; i < 3; i++ {
		fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	}

	resp := client.Get(t, "{{.ListPath}}")
	resp.RequireStatus(t, 200)
	assert.GreaterOrEqual(t, resp.DataLen(t), 3)
}
{{end}}{{if and .HasUpdate .HasGet .HasUpdateField}}
func TestGenerated{{.EntityName}}_Update(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	body := map[string]any{
		"{{.UpdateFieldJSON}}": {{.UpdateFieldTestVal}},
	}

	resp := client.Put(t, {{testPath .UpdatePath "created." .PKGoName}}, body)
	resp.RequireStatus(t, 200)

	// Verify via GET.
	getResp := client.Get(t, {{testPath .GetPath "created." .PKGoName}})
	getResp.RequireStatus(t, 200)
}
{{end}}{{if and .HasSoftDelete .HasGet}}
func TestGenerated{{.EntityName}}_SoftDelete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	resp := client.Put(t, {{testPath .SoftDeletePath "created." .PKGoName}}, nil)
	resp.RequireStatus(t, 204)
}
{{end}}{{if and .HasArchive .HasGet}}
func TestGenerated{{.EntityName}}_Archive(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	resp := client.Put(t, {{testPath .ArchivePath "created." .PKGoName}}, nil)
	resp.RequireStatus(t, 204)
}
{{end}}{{if and .HasRestore .HasGet}}
func TestGenerated{{.EntityName}}_Restore(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
{{if .HasArchive}}
	// Archive first, then restore.
	archiveResp := client.Put(t, {{testPath .ArchivePath "created." .PKGoName}}, nil)
	archiveResp.RequireStatus(t, 204)
{{end}}
	resp := client.Put(t, {{testPath .RestorePath "created." .PKGoName}}, nil)
	resp.RequireStatus(t, 204)
}
{{end}}{{if .HasDelete}}
func TestGenerated{{.EntityName}}_Delete(t *testing.T) {
	ctx, db, ts := setupTestServer(t)
	client := testhttp.New(ts.URL())

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	resp := client.Delete(t, {{testPath .DeletePath "created." .PKGoName}})
	resp.RequireStatus(t, 204)
{{if .HasGet}}
	// Verify it's gone.
	getResp := client.Get(t, {{testPath .GetPath "created." .PKGoName}})
	getResp.AssertStatus(t, 404)
{{end}}
}
{{end}}
`

const e2eTestBootstrapTemplate = `//go:build e2e

// This file is created once by gopernicus and will NOT be overwritten.
// Add custom E2E tests for {{.EntityName}} here.
//
// Use setupTestServer() from setup_test.go and testhttp.Client for requests:
//
//	func TestCustom{{.EntityName}}_BusinessLogic(t *testing.T) {
//		ctx, db, ts := setupTestServer(t)
//		client := testhttp.New(ts.URL())
//		// client.SetBearerToken(token)
//
//		created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
//		resp := client.Get(t, "/your/path/" + created.{{.PKGoName}})
//		resp.RequireStatus(t, 200)
//	}

package e2e
`
