package generators

const fixtureGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package fixtures

import (
	"context"
	"testing"
{{- range .Imports}}
	"{{.}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cryptids"
	"{{.FrameworkPath}}/infrastructure/testing/testpgx"
	"{{.FrameworkPath}}/sdk/conversion"
	"github.com/stretchr/testify/require"
)

// Ensure imports are used.
var (
	_ = conversion.Ptr[string]
	_ = time.Now
)
{{range $_, $e := .Entities}}
// =============================================================================
// {{$e.EntityName}}
// =============================================================================

// CreateTest{{$e.EntityName}} creates a test {{$e.EntityName}} with valid test data via direct SQL INSERT.
// Bypasses the repository layer for test isolation.
func CreateTest{{$e.EntityName}}(t *testing.T, ctx context.Context, db *testpgx.TestPGX{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
	require.NotNil(t, db)
{{range nonSelfRefParents $e.ParentFixtures}}
	require.NotEmpty(t, {{.VarName}}, "{{.VarName}} is required for {{$e.EntityName}}")
{{- end}}

	// Generate unique ID for unique field values.
	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID
{{if and (eq $e.PKGoType "string") (not $e.PKIsFK)}}
	{{camel $e.PKColumn}}, err := cryptids.GenerateID()
	require.NoError(t, err)
{{end}}{{if $e.HasPrincipalInheritance}}
	// Principal inheritance: insert into principals first.
	_, err = db.Pool.Exec(ctx, ` + "`" + `
		INSERT INTO principals (principal_id, principal_type, created_at)
		VALUES ($1, $2, NOW())
		ON CONFLICT (principal_id) DO NOTHING
	` + "`" + `, {{camel $e.PKColumn}}, "{{lower $e.EntityName}}")
	require.NoError(t, err, "failed to insert principal for {{$e.EntityName}}")
{{end}}
	// Insert directly via SQL (bypassing repository for test isolation).
	_, err = db.Pool.Exec(ctx, ` + "`" + `
		INSERT INTO {{$e.TableName}} ({{insertCols $e.InsertFields}})
		VALUES ({{positionalArgs (len $e.InsertFields)}})
	` + "`" + `,
		{{- range $e.InsertFields}}
		{{.TestDefault}},
		{{- end}}
	)
	require.NoError(t, err, "failed to insert {{$e.EntityName}}")

	// Retrieve the created record.
	var entity {{$e.RepoPkg}}.{{$e.EntityName}}
	err = db.Pool.QueryRow(ctx, ` + "`" + `
		SELECT {{selectCols $e.AllColumns}}
		FROM {{$e.TableName}}
		WHERE {{$e.PKColumn}} = $1
	` + "`" + `, {{camel $e.PKColumn}}).Scan(
		{{- range $e.AllColumns}}
		&entity.{{.GoName}},
		{{- end}}
	)
	require.NoError(t, err, "failed to retrieve created {{$e.EntityName}}")

	return entity
}

// CreateTest{{$e.EntityName}}WithDefaults creates a test {{$e.EntityName}} with auto-created FK dependencies.
// FK dependencies whose parent table is outside this generation batch are required as parameters.
func CreateTest{{$e.EntityName}}WithDefaults(t *testing.T, ctx context.Context, db *testpgx.TestPGX{{range outOfBatchParents $e.ParentFixtures}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
{{range inBatchParents $e.ParentFixtures}}
	parent{{.EntityName}} := CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	{{.VarName}} := parent{{.EntityName}}.{{.PKGoName}}
{{end}}
	return CreateTest{{$e.EntityName}}(t, ctx, db{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}}{{end}})
}
{{end}}`

const fixtureBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add custom fixture helpers here, such as:
// - Fixtures with specific test scenarios
// - Bulk fixture creation helpers
// - Fixtures with special data patterns

package fixtures
`
