package generators

// specFixtureGeneratedTemplate is the sqlite/spec-store variant of
// fixtureGeneratedTemplate: testsqlite handle instead of testpgx, `?`
// placeholders instead of $N, datetime('now') instead of NOW().
const specFixtureGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package sqlitefixtures

import (
	"context"
	"testing"
{{- range .Imports}}
	"{{.}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cryptids"
	"{{.FrameworkPath}}/infrastructure/database/crud"
	"{{.FrameworkPath}}/workshop/testing/testsqlite"
	"{{.FrameworkPath}}/sdk/conversion"
	"github.com/stretchr/testify/require"
)

// Ensure imports are used.
var (
	_ = conversion.Ptr[string]
{{- if .NeedsTime}}
	_ = time.Now
{{- end}}
)
{{range $_, $e := .Entities}}
// =============================================================================
// {{$e.EntityName}}
// =============================================================================

// CreateTest{{$e.EntityName}} creates a test {{$e.EntityName}} with valid test data via direct SQL INSERT.
// Bypasses the repository layer for test isolation.
func CreateTest{{$e.EntityName}}(t *testing.T, ctx context.Context, db *testsqlite.TestSQLite{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
	require.NotNil(t, db)
{{range nonSelfRefParents $e.ParentFixtures}}
	require.NotEmpty(t, {{.VarName}}, "{{.VarName}} is required for {{$e.EntityName}}")
{{- end}}

	// Generate unique ID for unique field values.
	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID
{{if and (eq $e.PKGoType "string") (not $e.PKIsFK)}}
	{{camel $e.PKColumn}}, err := cryptids.{{if $e.PKIsUUID}}GenerateUUID{{else}}GenerateID{{end}}()
	require.NoError(t, err)
{{end}}{{if $e.HasPrincipalInheritance}}
	// Principal inheritance: insert into principals first.
	_, err = db.DB.Exec(ctx, ` + "`" + `
		INSERT INTO principals (principal_id, principal_type, created_at)
		VALUES (?, ?, datetime('now'))
		ON CONFLICT (principal_id) DO NOTHING
	` + "`" + `, {{camel $e.PKColumn}}, "{{singularize $e.TableName}}")
	require.NoError(t, err, "failed to insert principal for {{$e.EntityName}}")
{{end}}
	// Insert directly via SQL (bypassing repository for test isolation).
	_, err = db.DB.Exec(ctx, ` + "`" + `
		INSERT INTO {{$e.TableName}} ({{insertCols $e.InsertFields}})
		VALUES ({{questionArgs (len $e.InsertFields)}})
	` + "`" + `,
		{{- range $e.InsertFields}}
		{{.TestDefault}},
		{{- end}}
	)
	require.NoError(t, err, "failed to insert {{$e.EntityName}}")

	// Retrieve the created record through the dialect-aware scanner —
	// sqlite TEXT timestamps must convert into time.Time entity fields.
	rows, err := db.Querier().Query(ctx, ` + "`" + `
		SELECT {{selectCols $e.AllColumns}}
		FROM {{$e.TableName}}
		WHERE {{$e.PKColumn}} = ?
	` + "`" + `, {{camel $e.PKColumn}})
	require.NoError(t, err, "failed to query created {{$e.EntityName}}")
	entity, err := crud.ScanOne[{{$e.RepoPkg}}.{{$e.EntityName}}](rows, db.Dialect())
	require.NoError(t, err, "failed to scan created {{$e.EntityName}}")

	return entity
}

// CreateTest{{$e.EntityName}}WithDefaults creates a test {{$e.EntityName}} with auto-created FK dependencies.
// FK dependencies whose parent table is outside this generation batch are required as parameters.
func CreateTest{{$e.EntityName}}WithDefaults(t *testing.T, ctx context.Context, db *testsqlite.TestSQLite{{range $e.AllExternalParams}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
{{range inBatchParents $e.ParentFixtures}}
	{{.VarName}}Parent := CreateTest{{.EntityName}}WithDefaults(t, ctx, db{{range .ForwardParams}}, {{.VarName}}{{end}})
	{{.VarName}} := {{.VarName}}Parent.{{.PKGoName}}
{{end}}
	return CreateTest{{$e.EntityName}}(t, ctx, db{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}}{{end}})
}
{{end}}`

const specFixtureBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add custom sqlite fixture helpers here, such as:
// - Fixtures with specific test scenarios
// - Bulk fixture creation helpers
// - Fixtures with special data patterns

package sqlitefixtures
`
