package generators

// fixtureGeneratedTemplate renders the test fixtures package for both store
// modes, branched on SpecMode: pgx (testpgx handle, $N placeholders, NOW())
// vs sqlite/spec (testsqlite handle, `?` placeholders, datetime('now'),
// dialect-aware scan back).
const fixtureGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{if .SpecMode}}sqlitefixtures{{else}}fixtures{{end}}

import (
	"context"
	"testing"
{{- range .Imports}}
	"{{.}}"
{{- end}}

	"{{.FrameworkPath}}/infrastructure/cryptids"
{{if .SpecMode}}	"{{.FrameworkPath}}/infrastructure/database/crud"
	"{{.FrameworkPath}}/workshop/testing/testsqlite"
{{else}}	"{{.FrameworkPath}}/workshop/testing/testpgx"
{{end}}	"{{.FrameworkPath}}/sdk/conversion"
	"github.com/stretchr/testify/require"
)

// Ensure imports are used.
var (
	_ = conversion.Ptr[string]
{{- if .NeedsTime}}
	_ = time.Now
{{- end}}
)
{{range $_, $e := .Entities}}
// =============================================================================
// {{$e.EntityName}}
// =============================================================================

// CreateTest{{$e.EntityName}} creates a test {{$e.EntityName}} with valid test data via direct SQL INSERT.
// Bypasses the repository layer for test isolation.
func CreateTest{{$e.EntityName}}(t *testing.T, ctx context.Context, db *{{if $.SpecMode}}testsqlite.TestSQLite{{else}}testpgx.TestPGX{{end}}{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
	require.NotNil(t, db)
{{range nonSelfRefParents $e.ParentFixtures}}
	require.NotEmpty(t, {{.VarName}}, "{{.VarName}} is required for {{$e.EntityName}}")
{{- end}}

	// Generate unique ID for unique field values.
	testUniqueID, err := cryptids.GenerateID()
	require.NoError(t, err)
	_ = testUniqueID
{{if and (eq $e.PKGoType "string") (not $e.PKIsFK)}}
	{{camel $e.PKColumn}}, err := cryptids.{{if $e.PKIsUUID}}GenerateUUID{{else}}GenerateID{{end}}()
	require.NoError(t, err)
{{end}}{{if $e.HasPrincipalInheritance}}
	// Principal inheritance: insert into principals first.
	_, err = db.{{if $.SpecMode}}DB{{else}}Pool{{end}}.Exec(ctx, ` + "`" + `
		INSERT INTO principals (principal_id, principal_type, created_at)
		VALUES {{if $.SpecMode}}(?, ?, datetime('now')){{else}}($1, $2, NOW()){{end}}
		ON CONFLICT (principal_id) DO NOTHING
	` + "`" + `, {{camel $e.PKColumn}}, "{{singularize $e.TableName}}")
	require.NoError(t, err, "failed to insert principal for {{$e.EntityName}}")
{{end}}
	// Insert directly via SQL (bypassing repository for test isolation).
	_, err = db.{{if $.SpecMode}}DB{{else}}Pool{{end}}.Exec(ctx, ` + "`" + `
		INSERT INTO {{$e.TableName}} ({{insertCols $e.InsertFields}})
		VALUES ({{if $.SpecMode}}{{questionArgs (len $e.InsertFields)}}{{else}}{{positionalArgs (len $e.InsertFields)}}{{end}})
	` + "`" + `,
		{{- range $e.InsertFields}}
		{{.TestDefault}},
		{{- end}}
	)
	require.NoError(t, err, "failed to insert {{$e.EntityName}}")

{{if $.SpecMode}}	// Retrieve the created record through the dialect-aware scanner —
	// sqlite TEXT timestamps must convert into time.Time entity fields.
	rows, err := db.Querier().Query(ctx, ` + "`" + `
		SELECT {{selectCols $e.AllColumns}}
		FROM {{$e.TableName}}
		WHERE {{$e.PKColumn}} = ?
	` + "`" + `, {{camel $e.PKColumn}})
	require.NoError(t, err, "failed to query created {{$e.EntityName}}")
	entity, err := crud.ScanOne[{{$e.RepoPkg}}.{{$e.EntityName}}](rows, db.Dialect())
	require.NoError(t, err, "failed to scan created {{$e.EntityName}}")
{{else}}	// Retrieve the created record.
	var entity {{$e.RepoPkg}}.{{$e.EntityName}}
	err = db.Pool.QueryRow(ctx, ` + "`" + `
		SELECT {{selectCols $e.AllColumns}}
		FROM {{$e.TableName}}
		WHERE {{$e.PKColumn}} = $1
	` + "`" + `, {{camel $e.PKColumn}}).Scan(
		{{- range $e.AllColumns}}
		&entity.{{.GoName}},
		{{- end}}
	)
	require.NoError(t, err, "failed to retrieve created {{$e.EntityName}}")
{{end}}
	return entity
}

// CreateTest{{$e.EntityName}}WithDefaults creates a test {{$e.EntityName}} with auto-created FK dependencies.
// FK dependencies whose parent table is outside this generation batch are required as parameters.
func CreateTest{{$e.EntityName}}WithDefaults(t *testing.T, ctx context.Context, db *{{if $.SpecMode}}testsqlite.TestSQLite{{else}}testpgx.TestPGX{{end}}{{range $e.AllExternalParams}}, {{.VarName}} string{{end}}) {{$e.RepoPkg}}.{{$e.EntityName}} {
	t.Helper()
{{range inBatchParents $e.ParentFixtures}}
	{{.VarName}}Parent := CreateTest{{.EntityName}}WithDefaults(t, ctx, db{{range .ForwardParams}}, {{.VarName}}{{end}})
	{{.VarName}} := {{.VarName}}Parent.{{.PKGoName}}
{{end}}
	return CreateTest{{$e.EntityName}}(t, ctx, db{{range nonSelfRefParents $e.ParentFixtures}}, {{.VarName}}{{end}})
}
{{end}}`

const fixtureBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add custom {{if .SpecMode}}sqlite {{end}}fixture helpers here, such as:
// - Fixtures with specific test scenarios
// - Bulk fixture creation helpers
// - Fixtures with special data patterns

package {{if .SpecMode}}sqlitefixtures{{else}}fixtures{{end}}
`
