package generators

// specIntegrationTestGeneratedTemplate is the spec-store variant of the pgx
// integration tests: testsqlite instead of testcontainers, sqlitefixtures
// instead of fixtures, NewStore(q, d, inTx) instead of NewStore(log, pool).
// Each setup opens a fresh file-backed database, so no truncation between
// tests is needed. Assertion bodies match the pgx variant — they are
// dialect-neutral by design.
const specIntegrationTestGeneratedTemplate = `//go:build integration

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.StorePkg}}

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
{{if .NeedsRepoImport}}
	"{{.RepoImport}}"
{{end}}
	fixtures "{{.FixtureImport}}"

	"{{.FrameworkPath}}/workshop/testing/testsqlite"
{{if .HasList}}	"{{.FrameworkPath}}/sdk/fop"
{{end}})

// Ensure imports are used.
var (
	_ = assert.Equal
)

// setupTestStore creates a fresh file-backed test database and store.
// migrateTestDB is defined in store_test.go (bootstrap file).
func setupTestStore(t *testing.T) (context.Context, *testsqlite.TestSQLite, *Store) {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping integration test")
	}

	ctx := context.Background()
	db := testsqlite.SetupTestSQLite(t, ctx, testsqlite.WithMigrations(migrateTestDB))
	store, err := NewStore(db.Querier(), db.Dialect(), TxRunner(db.TxRunner()))
	require.NoError(t, err)
	return ctx, db, store
}
{{if .HasCreate}}
func TestGenerated{{.EntityName}}Store_Create(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	_ = created

	// Verify the record was created and can be retrieved, every create
	// field intact (time fields excluded — encoding differs per dialect).
	result, err := store.Get(ctx, created.{{.PKGoName}}{{range .GetExtraCallArgs}}, {{.}}{{end}})
	require.NoError(t, err)
	assert.Equal(t, created.{{.PKGoName}}, result.{{.PKGoName}})
{{- range .RoundTripFields}}
	assert.Equal(t, created.{{.}}, result.{{.}})
{{- end}}
}
{{end}}{{if .HasGet}}
func TestGenerated{{.EntityName}}Store_Get(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	_ = created

	t.Run("found", func(t *testing.T) {
		result, err := store.Get(ctx, created.{{.PKGoName}}{{range .GetExtraCallArgs}}, {{.}}{{end}})
		require.NoError(t, err)
		assert.Equal(t, created.{{.PKGoName}}, result.{{.PKGoName}})
	})

	t.Run("not found", func(t *testing.T) {
		_, err := store.Get(ctx, "nonexistent-id"{{range .GetExtraCallArgs}}, {{.}}{{end}})
		require.Error(t, err)
	})
}
{{end}}{{if .HasList}}
func TestGenerated{{.EntityName}}Store_List(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	// Each fixture creates its own FK scope. When List filters by scope,
	// only the matching row is visible; assertions below reflect that.
	const numRecords = 3
	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	for i := 1; i < numRecords; i++ {
		fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	}
	_ = created

	t.Run("returns records", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		results, err := store.List(ctx, filter{{range .ListExtraCallArgs}}, {{.}}{{end}}, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)
		assert.GreaterOrEqual(t, len(results), 1)
	})

	t.Run("respects limit", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		page := fop.PageStringCursor{Limit: 2}
		results, err := store.List(ctx, filter{{range .ListExtraCallArgs}}, {{.}}{{end}}, orderBy, page, false)
		require.NoError(t, err)
		assert.LessOrEqual(t, len(results), 2)
	})

	t.Run("no duplicates", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		results, err := store.List(ctx, filter{{range .ListExtraCallArgs}}, {{.}}{{end}}, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)

		seen := make(map[string]bool)
		for _, r := range results {
			assert.False(t, seen[r.{{.PKGoName}}], "duplicate record: %s", r.{{.PKGoName}})
			seen[r.{{.PKGoName}}] = true
		}
	})
}
{{end}}{{if .HasHardDelete}}
func TestGenerated{{.EntityName}}Store_Delete(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	_ = created

	err := store.Delete(ctx, created.{{.PKGoName}}{{range .HardDeleteExtraCallArgs}}, {{.}}{{end}})
	require.NoError(t, err)

	// Verify record is gone.
	_, err = store.Get(ctx, created.{{.PKGoName}}{{range .GetExtraCallArgs}}, {{.}}{{end}})
	require.Error(t, err)
}
{{end}}{{if .HasSoftDelete}}
func TestGenerated{{.EntityName}}Store_SoftDelete(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)
	_ = created

	err := store.SoftDelete(ctx, created.{{.PKGoName}}{{range .SoftDeleteExtraCallArgs}}, {{.}}{{end}})
	require.NoError(t, err)

	// Verify record state changed.
	result, err := store.Get(ctx, created.{{.PKGoName}}{{range .GetExtraCallArgs}}, {{.}}{{end}})
	require.NoError(t, err)
	assert.Equal(t, "deleted", result.RecordState)
}
{{end}}{{if .HasDuplicateTest}}
func TestGenerated{{.EntityName}}Store_CreateDuplicate(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	// Re-creating with the same primary key must map to ErrAlreadyExists.
	input := {{.RepoPkg}}.Create{{.EntityName}}{
{{- range .CreateAssigns}}
		{{.}}: created.{{.}},
{{- end}}
	}
	_, err := store.Create(ctx, input)
	require.Error(t, err)
	assert.ErrorIs(t, err, {{.RepoPkg}}.Err{{.EntityName}}AlreadyExists)
}
{{end}}{{if .HasFKViolationTest}}
func TestGenerated{{.EntityName}}Store_CreateInvalidReference(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	// A create referencing a missing parent must map to ErrInvalidReference.
	input := {{.RepoPkg}}.Create{{.EntityName}}{
{{- range .CreateAssigns}}
		{{.}}: created.{{.}},
{{- end}}
	}
{{- if .PKReplacementExpr}}
	input.{{.PKGoName}} = {{.PKReplacementExpr}}
{{- end}}
	bogusFK := {{.FKViolationExpr}}
	input.{{.FKViolationGoName}} = {{if .FKViolationIsPointer}}&bogusFK{{else}}bogusFK{{end}}
	_, err := store.Create(ctx, input)
	require.Error(t, err)
	assert.ErrorIs(t, err, {{.RepoPkg}}.Err{{.EntityName}}InvalidReference)
}
{{end}}{{if .HasUpdateMutation}}
func TestGenerated{{.EntityName}}Store_Update(t *testing.T) {
	ctx, db, store := setupTestStore(t)

	created := fixtures.CreateTest{{.EntityName}}WithDefaults(t, ctx, db)

	newValue := "updated-value"
	result, err := store.Update(ctx, created.{{.PKGoName}}{{range .GetExtraCallArgs}}, {{.}}{{end}}, {{.RepoPkg}}.Update{{.EntityName}}{
		{{.UpdateFieldGoName}}: &newValue,
	})
	require.NoError(t, err)
{{- if .UpdateFieldEntityPointer}}
	require.NotNil(t, result.{{.UpdateFieldGoName}})
	assert.Equal(t, newValue, *result.{{.UpdateFieldGoName}})
{{- else}}
	assert.Equal(t, newValue, result.{{.UpdateFieldGoName}})
{{- end}}
}
{{end}}
`

const specIntegrationTestBootstrapTemplate = `//go:build integration

// This file is created once by gopernicus and will NOT be overwritten.
// Add custom integration tests for the {{.EntityName}} store here.
//
// The setupTestStore() helper in generated_test.go provides a fresh
// file-backed test database and store instance per call.

package {{.StorePkg}}

import (
	"context"
	"os"
	"path/filepath"
	"runtime"

	"{{.FrameworkPath}}/infrastructure/database/sqlite/moderncdb"
)

// migrateTestDB applies this project's migrations to the test database, so
// tests run against the same schema as 'gopernicus db migrate'. Replace it
// if this store's tests need a different schema setup.
func migrateTestDB(ctx context.Context, db *moderncdb.DB) error {
	return moderncdb.RunMigrations(ctx, db, os.DirFS(projectRoot()), "{{.MigrationsDir}}")
}

// projectRoot walks up from this source file to the directory containing
// go.mod, so the migrations path resolves at any test working directory.
func projectRoot() string {
	_, file, _, _ := runtime.Caller(0)
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "."
		}
		dir = parent
	}
}
`
