package generators

const integrationTestGeneratedTemplate = `//go:build integration

// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.StorePkg}}

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
{{if .HasList}}
	"{{.RepoImport}}"
{{end}}
	fixtures "{{.FixtureImport}}"

	"github.com/gopernicus/gopernicus/infrastructure/testing/pgxfixtures"
	"github.com/gopernicus/gopernicus/infrastructure/testing/testpgx"
{{if .HasList}}	"github.com/gopernicus/gopernicus/sdk/fop"
{{end}}	"github.com/gopernicus/gopernicus/sdk/logger"
)

// Ensure imports are used.
var (
	_ = assert.Equal
)

// setupTestStore creates a test database and store for integration tests.
// migrateTestDB must be defined in store_test.go (bootstrap file).
func setupTestStore(t *testing.T) (context.Context, *testpgx.TestPGX, *Store) {
	t.Helper()

	if testing.Short() {
		t.Skip("skipping integration test")
	}

	ctx := context.Background()
	db := testpgx.SetupTestPGX(t, ctx, testpgx.WithMigrations(migrateTestDB))
	store := NewStore(logger.NewNoop(), db.Pool)
	return ctx, db, store
}
{{if .HasCreate}}
func TestGenerated{{.EntityName}}Store_Create(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTest{{.EntityName}}(t, ctx, db)

	// Verify the record was created and can be retrieved.
	result, err := store.Get(ctx, created.{{.PKGoName}})
	require.NoError(t, err)
	assert.Equal(t, created.{{.PKGoName}}, result.{{.PKGoName}})
}
{{end}}{{if .HasGet}}
func TestGenerated{{.EntityName}}Store_Get(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTest{{.EntityName}}(t, ctx, db)

	t.Run("found", func(t *testing.T) {
		result, err := store.Get(ctx, created.{{.PKGoName}})
		require.NoError(t, err)
		assert.Equal(t, created.{{.PKGoName}}, result.{{.PKGoName}})
	})

	t.Run("not found", func(t *testing.T) {
		_, err := store.Get(ctx, "nonexistent-id")
		require.Error(t, err)
	})
}
{{end}}{{if .HasList}}
func TestGenerated{{.EntityName}}Store_List(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	// Create multiple records.
	const numRecords = 3
	for i := 0; i < numRecords; i++ {
		fixtures.CreateTest{{.EntityName}}(t, ctx, db)
	}

	t.Run("returns all records", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		results, err := store.List(ctx, filter, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)
		assert.GreaterOrEqual(t, len(results), numRecords)
	})

	t.Run("respects limit", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		page := fop.PageStringCursor{Limit: 2}
		results, err := store.List(ctx, filter, orderBy, page, false)
		require.NoError(t, err)
		assert.LessOrEqual(t, len(results), 2)
	})

	t.Run("no duplicates", func(t *testing.T) {
		filter := {{.RepoPkg}}.FilterList{}
		orderBy := fop.NewOrder({{.RepoPkg}}.DefaultOrderBy, {{.RepoPkg}}.DefaultOrderDirection)
		results, err := store.List(ctx, filter, orderBy, fop.PageStringCursor{}, false)
		require.NoError(t, err)

		seen := make(map[string]bool)
		for _, r := range results {
			assert.False(t, seen[r.{{.PKGoName}}], "duplicate record: %s", r.{{.PKGoName}})
			seen[r.{{.PKGoName}}] = true
		}
	})
}
{{end}}{{if .HasHardDelete}}
func TestGenerated{{.EntityName}}Store_Delete(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTest{{.EntityName}}(t, ctx, db)

	err := store.Delete(ctx, created.{{.PKGoName}})
	require.NoError(t, err)

	// Verify record is gone.
	_, err = store.Get(ctx, created.{{.PKGoName}})
	require.Error(t, err)
}
{{end}}{{if .HasSoftDelete}}
func TestGenerated{{.EntityName}}Store_SoftDelete(t *testing.T) {
	ctx, db, store := setupTestStore(t)
	pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)

	created := fixtures.CreateTest{{.EntityName}}(t, ctx, db)

	err := store.SoftDelete(ctx, created.{{.PKGoName}})
	require.NoError(t, err)

	// Verify record state changed.
	result, err := store.Get(ctx, created.{{.PKGoName}})
	require.NoError(t, err)
	assert.Equal(t, "deleted", result.RecordState)
}
{{end}}
`

const integrationTestBootstrapTemplate = `//go:build integration

// This file is created once by gopernicus and will NOT be overwritten.
// Add custom integration tests for the {{.EntityName}} store here.
//
// The setupTestStore() helper in generated_test.go provides a test database
// and store instance. Use it as the basis for custom tests:
//
//	func TestStore_MyCustomQuery(t *testing.T) {
//		ctx, db, store := setupTestStore(t)
//		pgxfixtures.TruncatePublicSchema(t, ctx, db.Pool)
//		// ... test custom store methods
//	}

package {{.StorePkg}}

import (
	"context"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
)

// migrateTestDB runs migrations for the test database.
// TODO: Update this to use your project's migration embed.
//
// Example with embedded migrations:
//
//	//go:embed ../../../../workshop/migrations/primary/*.sql
//	var testMigrations embed.FS
//
//	func migrateTestDB(ctx context.Context, pool *pgxdb.Pool) error {
//		return pgxdb.RunMigrations(ctx, pool, testMigrations, "workshop/migrations/primary")
//	}
func migrateTestDB(_ context.Context, _ *pgxdb.Pool) error {
	// Replace with actual migration logic.
	return nil
}
`
