package generators

const storeGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.

package {{.PackageName}}

import (
{{- if or .HasList .HasUpdate}}
	"bytes"
{{- end}}
	"context"
	"errors"
	"fmt"
	"log/slog"
{{- if or .HasUpdate .HasList}}
	"strings"
{{- end}}
{{- if .NeedsTime}}
	"time"
{{- end}}

	"github.com/jackc/pgx/v5"

	"github.com/gopernicus/gopernicus/infrastructure/database/postgres/pgxdb"
{{- if .HasList}}
	"github.com/gopernicus/gopernicus/sdk/fop"
{{- end}}

	"{{.RepoImport}}"
)

// Store implements {{.RepoPkg}}.Storer using PostgreSQL via pgx.
type Store struct {
	log *slog.Logger
	db  pgxdb.Querier
}

// NewStore creates a new {{.RepoPkg}} store backed by the given Querier.
// Querier is satisfied by both *pgxpool.Pool and pgx.Tx, enabling
// transaction composition.
func NewStore(log *slog.Logger, db pgxdb.Querier) *Store {
	return &Store{log: log, db: db}
}

// compile-time interface check (Storer is defined in repository.go)
var _ {{.RepoPkg}}.Storer = (*Store)(nil)

// ─── error mapping ────────────────────────────────────────────────────────────

func (s *Store) mapError(err error) error {
	dbErr := pgxdb.HandlePgError(err)
	switch {
	case errors.Is(dbErr, pgxdb.ErrDBDuplicatedEntry):
		return {{.RepoPkg}}.Err{{.EntityName}}AlreadyExists
	case errors.Is(dbErr, pgxdb.ErrDBForeignKeyViolation):
		return {{.RepoPkg}}.Err{{.EntityName}}InvalidReference
	case errors.Is(dbErr, pgxdb.ErrDBCheckViolation),
		errors.Is(dbErr, pgxdb.ErrDBNotNullViolation):
		return {{.RepoPkg}}.Err{{.EntityName}}InvalidInput
	default:
		return dbErr
	}
}

// ─── methods ──────────────────────────────────────────────────────────────────
{{range .Methods}}
{{- if eq .Category "scan_one_custom"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	query := ` + "`" + `{{.SQL}}` + "`" + `

	args := pgx.NamedArgs{
{{- range .NamedArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return {{.ReturnTypeName}}{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[{{.ReturnTypeName}}])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return {{.ReturnTypeName}}{}, {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
		}
		return {{.ReturnTypeName}}{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}
{{- else if eq .Category "scan_many"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	query := ` + "`" + `{{.SQL}}` + "`" + `

	args := pgx.NamedArgs{
{{- range .NamedArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	return pgx.CollectRows(rows, pgx.RowToStructByName[{{$.RepoPkg}}.{{$.EntityName}}])
}
{{- else if eq .Category "scan_one"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	query := ` + "`" + `{{.SQL}}` + "`" + `

	args := pgx.NamedArgs{
{{- range .NamedArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return {{$.RepoPkg}}.{{$.EntityName}}{}, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[{{$.RepoPkg}}.{{$.EntityName}}])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return {{$.RepoPkg}}.{{$.EntityName}}{}, {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
		}
		return {{$.RepoPkg}}.{{$.EntityName}}{}, pgxdb.HandlePgError(err)
	}

	return record, nil
}
{{- else if eq .Category "exec"}}

func (s *Store) {{.FuncName}}({{.Params}}) error {
	args := pgx.NamedArgs{
{{- range .ExecArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
	}

	query := ` + "`" + `{{.ExecSQL}}` + "`" + `

{{- if .SkipRowCheck}}
	_, err := s.db.Exec(ctx, query, args)
{{- else}}
	result, err := s.db.Exec(ctx, query, args)
{{- end}}
	if err != nil {
		return pgxdb.HandlePgError(err)
	}
{{- if not .SkipRowCheck}}

	if result.RowsAffected() == 0 {
		return {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
	}
{{- end}}

	return nil
}
{{- else if eq .Category "create"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
{{- if or .HasAppCreatedAt .HasAppUpdatedAt}}
	now := time.Now().UTC()
{{- end}}
	query := ` + "`" + `INSERT INTO {{$.QualifiedTable}} ({{.InsertCols}}{{if .HasAppCreatedAt}}, created_at{{end}}{{if .HasAppUpdatedAt}}, updated_at{{end}})
		VALUES ({{.InsertVals}}{{if .HasAppCreatedAt}}, @_created_at{{end}}{{if .HasAppUpdatedAt}}, @_updated_at{{end}})
		RETURNING {{$.AllCols}}` + "`" + `

	args := pgx.NamedArgs{
{{- range .CreateArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
{{- if .HasAppCreatedAt}}
		"_created_at": now,
{{- end}}
{{- if .HasAppUpdatedAt}}
		"_updated_at": now,
{{- end}}
	}

	rows, err := s.db.Query(ctx, query, args)
	if err != nil {
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapError(err)
	}
	defer rows.Close()

	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[{{$.RepoPkg}}.{{$.EntityName}}])
	if err != nil {
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapError(err)
	}

	return record, nil
}
{{- else if eq .Category "update"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	buf := bytes.NewBufferString("UPDATE {{$.QualifiedTable}} SET ")
	args := pgx.NamedArgs{
		"{{.WhereField}}": {{.WhereGoVar}},
	}
	var setClauses []string
{{- range .UpdateFields}}
	if input.{{.GoName}} != nil {
		setClauses = append(setClauses, "{{.DBName}} = @{{.DBName}}")
		args["{{.DBName}}"] = *input.{{.GoName}}
	}
{{- end}}
{{- if .HasUpdatedAt}}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}
{{- end}}

	if len(setClauses) == 0 {
		return fmt.Errorf("no fields to update")
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE {{.WhereField}} = @{{.WhereField}}")

	result, err := s.db.Exec(ctx, buf.String(), args)
	if err != nil {
		return s.mapError(err)
	}

	if result.RowsAffected() == 0 {
		return {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
	}

	return nil
}
{{- else if eq .Category "update_returning"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	buf := bytes.NewBufferString("UPDATE {{$.QualifiedTable}} SET ")
	args := pgx.NamedArgs{
		"{{.WhereField}}": {{.WhereGoVar}},
	}
	var setClauses []string
{{- range .UpdateFields}}
	if input.{{.GoName}} != nil {
		setClauses = append(setClauses, "{{.DBName}} = @{{.DBName}}")
		args["{{.DBName}}"] = *input.{{.GoName}}
	}
{{- end}}
{{- if .HasUpdatedAt}}

	// Auto-set updated_at if not explicitly provided.
	if input.UpdatedAt == nil {
		setClauses = append(setClauses, "updated_at = @updated_at")
		args["updated_at"] = time.Now().UTC()
	}
{{- end}}

	if len(setClauses) == 0 {
{{- if .ReturnTypeName}}
		return {{.ReturnTypeName}}{}, fmt.Errorf("no fields to update")
{{- else}}
		return {{$.RepoPkg}}.{{$.EntityName}}{}, fmt.Errorf("no fields to update")
{{- end}}
	}

	buf.WriteString(strings.Join(setClauses, ", "))
	buf.WriteString(" WHERE {{.WhereField}} = @{{.WhereField}}")
	buf.WriteString(" RETURNING {{.UpdateReturningCols}}")

	rows, err := s.db.Query(ctx, buf.String(), args)
	if err != nil {
{{- if .ReturnTypeName}}
		return {{.ReturnTypeName}}{}, s.mapError(err)
{{- else}}
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapError(err)
{{- end}}
	}
	defer rows.Close()

{{- if .ReturnTypeName}}
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[{{.ReturnTypeName}}])
{{- else}}
	record, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[{{$.RepoPkg}}.{{$.EntityName}}])
{{- end}}
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
{{- if .ReturnTypeName}}
			return {{.ReturnTypeName}}{}, {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
{{- else}}
			return {{$.RepoPkg}}.{{$.EntityName}}{}, {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
{{- end}}
		}
{{- if .ReturnTypeName}}
		return {{.ReturnTypeName}}{}, s.mapError(err)
{{- else}}
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapError(err)
{{- end}}
	}

	return record, nil
}
{{- else if eq .Category "list"}}

func (s *Store) {{.FuncName}}({{.Params}}) {{.Returns}} {
	data := pgx.NamedArgs{
{{- range .BaseArgs}}
		"{{.ArgName}}": {{.GoExpr}},
{{- end}}
	}

	baseSQL := ` + "`" + `{{.BaseSQL}}` + "`" + `
{{- if .HasFilters}}
{{- range .Filters}}
	baseSQL = replaceFilterPlaceholder(baseSQL, "${{.PlaceholderName}}", {{.GenFuncName}}(filter, data))
{{- end}}
{{- if .HasSearch}}
	baseSQL = replaceFilterPlaceholder(baseSQL, "$search", {{.GenSearchFunc}}(filter, data))
{{- end}}
{{- end}}

	buf := bytes.NewBufferString(baseSQL)
{{- if .HasOrder}}

	// Resolve order field.
	of, ok := {{$.RepoPkg}}.OrderByFields[orderBy.Field]
	if !ok {
		of = {{$.RepoPkg}}.OrderByFields[{{$.RepoPkg}}.DefaultOrderBy]
	}

	// Apply cursor pagination.
	if page.Cursor != "" {
		err := pgxdb.ApplyCursorPaginationFromToken(buf, data, pgxdb.CursorConfig{
			Cursor:     page.Cursor,
			OrderField: of.Column,
			PKField:    "{{$.PKColumn}}",
			Direction:  orderBy.Direction,
			Limit:      page.Limit,
			CastLower:  of.CastLower,
		}, forPrevious)
		if err != nil {
			return nil, fmt.Errorf("cursor pagination: %w", err)
		}
	}

	if err := pgxdb.AddOrderByClauseWithOptions(buf, of.Column, "{{$.PKColumn}}", orderBy.Direction, forPrevious, of.CastLower); err != nil {
		return nil, fmt.Errorf("order: %w", err)
	}

	pgxdb.AddLimitClause(page.Limit, data, buf)
{{- else if .HasLimit}}

	pgxdb.AddLimitClause(limit, data, buf)
{{- end}}

	rows, err := s.db.Query(ctx, buf.String(), data)
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
	defer rows.Close()

{{- if .ListReturnType}}
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[{{.ListReturnType}}])
{{- else}}
	entities, err := pgx.CollectRows(rows, pgx.RowToStructByName[{{$.RepoPkg}}.{{$.EntityName}}])
{{- end}}
	if err != nil {
		return nil, pgxdb.HandlePgError(err)
	}
{{- if .HasOrder}}

	// Reverse for previous page.
	if forPrevious && len(entities) > 0 {
		for i, j := 0, len(entities)-1; i < j; i, j = i+1, j-1 {
			entities[i], entities[j] = entities[j], entities[i]
		}
	}
{{- end}}

	return entities, nil
}
{{- end}}
{{- end}}

// ─── filter placeholder substitution ─────────────────────────────────────────

func replaceFilterPlaceholder(sql, placeholder, fragment string) string {
	if fragment == "" {
		fragment = "TRUE"
	}
	return strings.Replace(sql, placeholder, "("+fragment+")", 1)
}

// ─── per-function named filters ──────────────────────────────────────────────
{{range .Methods}}
{{- if and (eq .Category "list") .HasFilters}}
{{- range .Filters}}

func {{.GenFuncName}}(filter {{$.RepoPkg}}.{{.FilterTypeName}}, data pgx.NamedArgs) string {
	var conditions []string
{{- if .HasRecordState}}

	// Auto-default record_state to 'active'.
	if filter.RecordState == nil {
		conditions = append(conditions, "{{.RecordStateSQLName}} = @record_state")
		data["record_state"] = "active"
	} else if strings.Contains(*filter.RecordState, ",") {
		states := strings.Split(*filter.RecordState, ",")
		for i := range states {
			states[i] = strings.TrimSpace(states[i])
		}
		conditions = append(conditions, "{{.RecordStateSQLName}} = ANY(@record_states)")
		data["record_states"] = states
	} else {
		conditions = append(conditions, "{{.RecordStateSQLName}} = @record_state")
		data["record_state"] = *filter.RecordState
	}
{{- end}}
{{- range .Fields}}
{{- if eq .DBName "record_state"}}
{{- else}}
	if filter.{{.GoName}} != nil {
		conditions = append(conditions, "{{.SQLName}} = @filter_{{.DBName}}")
		data["filter_{{.DBName}}"] = *filter.{{.GoName}}
	}
{{- if .IsTime}}
	if filter.{{.GoName}}After != nil {
		conditions = append(conditions, "{{.SQLName}} >= @filter_{{.DBName}}_after")
		data["filter_{{.DBName}}_after"] = *filter.{{.GoName}}After
	}
	if filter.{{.GoName}}Before != nil {
		conditions = append(conditions, "{{.SQLName}} <= @filter_{{.DBName}}_before")
		data["filter_{{.DBName}}_before"] = *filter.{{.GoName}}Before
	}
{{- end}}
{{- end}}
{{- end}}

	// Prefilter authorization: restrict to authorized IDs.
	// nil = unrestricted (admin bypass, no filter applied).
	// empty non-nil = no access (WHERE pk = ANY('{}') returns zero rows).
	if filter.AuthorizedIDs != nil {
		conditions = append(conditions, "{{$.PKColumn}} = ANY(@authorized_ids)")
		data["authorized_ids"] = filter.AuthorizedIDs
	}

	if len(conditions) == 0 {
		return "TRUE"
	}
	return strings.Join(conditions, " AND ")
}
{{- end}}
{{- if .HasSearch}}

func {{.GenSearchFunc}}(filter {{$.RepoPkg}}.{{.FilterTypeName}}, data pgx.NamedArgs) string {
	if filter.SearchTerm == nil || *filter.SearchTerm == "" {
		return "TRUE"
	}
{{- if eq .SearchType "web_search"}}
	// Full-text search using websearch_to_tsquery.
	var tsvParts []string
{{- range .SearchFields}}
	tsvParts = append(tsvParts, "coalesce({{.SQLName}}, '')")
{{- end}}
	tsvExpr := "to_tsvector('english', " + strings.Join(tsvParts, " || ' ' || ") + ")"
	data["search_term"] = *filter.SearchTerm
	return tsvExpr + " @@ websearch_to_tsquery('english', @search_term)"
{{- else if eq .SearchType "tsvector"}}
	// Full-text search against pre-computed tsvector column.
	data["search_term"] = *filter.SearchTerm
{{- range .SearchFields}}
	return "{{.SQLName}} @@ websearch_to_tsquery('english', @search_term)"
{{- end}}
{{- else}}
	// ILIKE pattern search.
	searchPattern := "%" + *filter.SearchTerm + "%"
	data["search_term"] = searchPattern
	var searchConditions []string
{{- range .SearchFields}}
	searchConditions = append(searchConditions, "{{.SQLName}} ILIKE @search_term")
{{- end}}
	if len(searchConditions) == 0 {
		return "TRUE"
	}
	return strings.Join(searchConditions, " OR ")
{{- end}}
}
{{- end}}
{{- end}}
{{- end}}

// Ensure imports are used.
var _ = errors.New
var _ = fmt.Sprintf
var _ slog.Logger
var _ pgxdb.Querier
{{- if .HasList}}
var _ fop.Order
{{- end}}
`

const storeBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add custom store methods here. Store is defined in generated.go.
//
// Example:
//
//	func (s *Store) MyCustomQuery(ctx context.Context, id string) ({{.RepoPkg}}.{{.EntityName}}, error) {
//		rows, err := s.db.Query(ctx, ` + "`" + `SELECT ... FROM ... WHERE id = @id` + "`" + `, pgx.NamedArgs{"id": id})
//		if err != nil {
//			return {{.RepoPkg}}.{{.EntityName}}{}, err
//		}
//		defer rows.Close()
//		return pgx.CollectOneRow(rows, pgx.RowToStructByName[{{.RepoPkg}}.{{.EntityName}}])
//	}

package {{.PackageName}}
`

// storeFopTemplate is no longer used — filter functions are called directly
// from generated.go without wrapper indirection.
const storeFopTemplate = ``
