package generators

// =============================================================================
// Flat repository generated.go template — ALWAYS REGENERATED
//
// Key differences from embedded (v1) template:
// - Types use final names: Entity, CreateEntity, Storer (no GeneratedX prefix)
// - Repository struct and all methods are in this file (no GeneratedRepository)
// - No model.go wrapper types needed
// - OrderByFields is direct (no GeneratedOrderByFields indirection)
// =============================================================================

const repoGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// This file is regenerated every time 'gopernicus generate' runs.

package {{.PackageName}}

import (
	"context"
	"fmt"
	"time"
{{- range .ExtraImports}}
	"{{.}}"
{{- end}}

	"github.com/gopernicus/gopernicus/sdk/errs"
	"github.com/gopernicus/gopernicus/sdk/fop"
{{- if .HasEvents}}
	"github.com/gopernicus/gopernicus/infrastructure/events"
{{- end}}
)

// =============================================================================
// Errors
// =============================================================================

var (
	Err{{.EntityName}}NotFound         = fmt.Errorf("{{.EntityNameSpaced}}: %w", errs.ErrNotFound)
	Err{{.EntityName}}AlreadyExists    = fmt.Errorf("{{.EntityNameSpaced}}: %w", errs.ErrAlreadyExists)
	Err{{.EntityName}}InvalidReference = fmt.Errorf("{{.EntityNameSpaced}}: %w", errs.ErrInvalidReference)
	Err{{.EntityName}}InvalidInput     = fmt.Errorf("{{.EntityNameSpaced}}: %w", errs.ErrInvalidInput)
)

// =============================================================================
// OrderBy constants
// =============================================================================

const (
	OrderByPK = "{{.PKColumn}}"
{{- range .OrderByFields}}
	{{.ConstName}} = "{{.DBColumn}}"
{{- end}}
)

// OrderByFields maps user-facing field names to OrderField definitions.
var OrderByFields = map[string]fop.OrderField{
	OrderByPK: {Column: "{{.PKColumn}}"},
{{- range .OrderByFields}}
	{{.ConstName}}: {Column: "{{.DBColumn}}"{{if .CastLower}}, CastLower: true{{end}}},
{{- end}}
}

// =============================================================================
// Max page limits (from @max annotations)
// =============================================================================
{{range .Methods}}
{{- if and (eq .Category "list") .MaxLimit}}
const MaxLimit{{.Name}} = {{.MaxLimit}}
{{- end}}
{{- end}}

// =============================================================================
// Entity struct
// =============================================================================

// {{.EntityName}} is the database entity.
type {{.EntityName}} struct {
{{- range .EntityFields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.DBName}}" db:"{{.DBName}}"` + "`" + `
{{- end}}
}

// =============================================================================
// Input structs
// =============================================================================
{{if .HasCreate}}
// {{.CreateName}} is the input for creating a {{.EntityNameLower}}.
type {{.CreateName}} struct {
{{- range .CreateFields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.DBName}},omitempty"` + "`" + `
{{- end}}
}
{{end}}
{{- if .HasUpdate}}
// {{.UpdateName}} is the input for updating a {{.EntityNameLower}}.
type {{.UpdateName}} struct {
{{- range .UpdateFields}}
	{{.GoName}} *{{.GoType}} ` + "`" + `json:"{{.DBName}},omitempty"` + "`" + `
{{- end}}
}
{{end}}
// =============================================================================
// Filter structs
// =============================================================================
{{range .Filters}}
// {{.FilterTypeName}} holds filter criteria for {{.FuncName}}.
type {{.FilterTypeName}} struct {
{{- range .Fields}}
	{{.GoName}} *{{.GoType}} ` + "`" + `json:"{{.DBName}},omitempty"` + "`" + `
{{- if .IsTime}}
	{{.GoName}}After  *time.Time ` + "`" + `json:"{{.DBName}}_after,omitempty"` + "`" + `
	{{.GoName}}Before *time.Time ` + "`" + `json:"{{.DBName}}_before,omitempty"` + "`" + `
{{- end}}
{{- end}}
{{- if .HasSearchTerm}}
	SearchTerm *string ` + "`" + `json:"search_term,omitempty"` + "`" + `
{{- end}}

	// AuthorizedIDs restricts results to the given primary key values.
	// Set by the bridge layer for prefilter authorization (authorization-scoped listings).
	// Nil means unrestricted (admin bypass). Empty non-nil means no access.
	AuthorizedIDs []string ` + "`" + `json:"-"` + "`" + `
}
{{end}}
// =============================================================================
// Custom result structs
// =============================================================================
{{range .Methods}}
{{- if and .ReturnTypeName .ReturnFields}}
// {{.ReturnTypeName}} is the result type for {{.Name}}.
type {{.ReturnTypeName}} struct {
{{- range .ReturnFields}}
	{{.GoName}} {{.GoType}} ` + "`" + `json:"{{.DBName}}" db:"{{.DBName}}"` + "`" + `
{{- end}}
}
{{end}}
{{- end}}
{{- if .HasEvents}}
// =============================================================================
// Event structs
// =============================================================================
{{range .Events}}
{{- if eq .Category "create"}}
// {{.AliasName}} is emitted when a {{$.EntityNameLower}} is created.
type {{.AliasName}} struct {
	events.BaseEvent
	{{.EntityName}} {{.EntityName}} ` + "`" + `json:"{{$.EntityNameLower}}"` + "`" + `
}
{{- else if eq .Category "update"}}
// {{.AliasName}} is emitted when a {{$.EntityNameLower}} is updated.
type {{.AliasName}} struct {
	events.BaseEvent
	{{.PKGoName}} {{.PKGoType}} ` + "`" + `json:"{{.PKDBName}}"` + "`" + `
	Update {{.UpdateName}} ` + "`" + `json:"update"` + "`" + `
}
{{- else if .IsDelete}}
// {{.AliasName}} is emitted when a {{$.EntityNameLower}} is deleted.
type {{.AliasName}} struct {
	events.BaseEvent
	{{.PKGoName}} {{.PKGoType}} ` + "`" + `json:"{{.PKDBName}}"` + "`" + `
	Permanent bool ` + "`" + `json:"permanent"` + "`" + `
}
{{- else}}
// {{.AliasName}} is emitted by {{$.EntityName}}.
type {{.AliasName}} struct {
	events.BaseEvent
	{{.PKGoName}} {{.PKGoType}} ` + "`" + `json:"{{.PKDBName}}"` + "`" + `
}
{{- end}}
{{end}}
{{- end}}
{{if .HasList}}
// =============================================================================
// Cursor helpers
// =============================================================================

func Encode{{.EntityName}}Cursor(record {{.EntityName}}, orderField string) (string, error) {
	orderValue := Get{{.EntityName}}OrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.{{.PKGoName}})
}

func Get{{.EntityName}}OrderValue(record {{.EntityName}}, field string) any {
	switch field {
{{- range .CursorFields}}
	case "{{.DBName}}":
		return record.{{.GoName}}
{{- end}}
	default:
		return record.{{.PKGoName}}
	}
}
{{range .Methods}}
{{- if and .ListReturnType .HasOrder .ReturnFields}}

func Encode{{.Name}}ResultCursor(record {{.ListReturnType}}, orderField string) (string, error) {
	orderValue := Get{{.Name}}ResultOrderValue(record, orderField)
	return fop.EncodeCursor(orderField, orderValue, record.{{$.PKGoName}})
}

func Get{{.Name}}ResultOrderValue(record {{.ListReturnType}}, field string) any {
	switch field {
{{- range .ReturnFields}}
	case "{{.DBName}}":
		return record.{{.GoName}}
{{- end}}
	default:
		return record.{{$.PKGoName}}
	}
}
{{- end}}
{{- end}}
{{end}}
// =============================================================================
// Repository methods (generated from queries.sql)
// =============================================================================
{{range .Methods}}
{{- if and (eq .Category "list") .HasFilters .HasOrder}}
// {{.Name}} queries the store and wraps the result with pagination metadata.
func (r *Repository) {{.Name}}(ctx context.Context, filter {{.FilterTypeName}}, {{if .ExplicitParams}}{{.ExplicitParams}}, {{end}}orderBy fop.Order, page fop.PageStringCursor) ([]{{if .ListReturnType}}{{.ListReturnType}}{{else}}{{$.EntityName}}{{end}}, fop.Pagination, error) {
	if orderBy.Field == "" {
		orderBy = fop.NewOrder(DefaultOrderBy, DefaultOrderDirection)
	}
	orderField := orderBy.Field

	// Over-fetch by one to detect next page.
	listPage := fop.PageStringCursor{
		Limit:  page.Limit + 1,
		Cursor: page.Cursor,
	}

	records, err := r.store.{{.Name}}(ctx, filter, {{if .ExplicitCallArgs}}{{.ExplicitCallArgs}}, {{end}}orderBy, listPage, false)
	if err != nil {
		return nil, fop.Pagination{}, fmt.Errorf("query: %w", err)
	}

	returnableRecords := records
	nextCursor := ""

	if len(records) > page.Limit {
		returnableRecords = records[:page.Limit]
		lastRecord := returnableRecords[len(returnableRecords)-1]
{{- if .ListReturnType}}
		nextCursor, err = Encode{{.Name}}ResultCursor(lastRecord, orderField)
{{- else}}
		nextCursor, err = Encode{{$.EntityName}}Cursor(lastRecord, orderField)
{{- end}}
		if err != nil {
			return nil, fop.Pagination{}, fmt.Errorf("encode next cursor: %w", err)
		}
	}

	pagination := fop.Pagination{
		Limit:      page.Limit,
		NextCursor: nextCursor,
		PageTotal:  len(returnableRecords),
	}

	// Check for previous page when a cursor was provided.
	if page.Cursor != "" {
		prevRecords, err := r.store.{{.Name}}(ctx, filter, {{if .ExplicitCallArgs}}{{.ExplicitCallArgs}}, {{end}}orderBy, page, true)
		if err == nil && len(prevRecords) > 0 {
			pagination.HasPrev = true
			if len(prevRecords) == page.Limit {
				firstRecord := prevRecords[0]
{{- if .ListReturnType}}
				pagination.PreviousCursor, err = Encode{{.Name}}ResultCursor(firstRecord, orderField)
{{- else}}
				pagination.PreviousCursor, err = Encode{{$.EntityName}}Cursor(firstRecord, orderField)
{{- end}}
				if err != nil {
					return nil, fop.Pagination{}, fmt.Errorf("encode prev cursor: %w", err)
				}
			}
		}
	}

	return returnableRecords, pagination, nil
}
{{- else if and (eq .Category "list") .HasFilters}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) {{.Returns}} {
	records, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return nil, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
	return records, nil
}
{{- else if eq .Category "list"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) {{.Returns}} {
	records, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return nil, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
	return records, nil
}
{{- else if eq .Category "create"}}
// {{.Name}} generates an ID, sets defaults, and delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) ({{$.EntityName}}, error) {
{{- if $.HasPKInCreate}}
	if input.{{$.PKGoName}} == "" {
		id, err := r.generateID()
		if err != nil {
			return {{$.EntityName}}{}, fmt.Errorf("generate id: %w", err)
		}
		input.{{$.PKGoName}} = id
	}
{{- end}}
{{- if $.HasSoftDelete}}
	if input.RecordState == "" {
		input.RecordState = "active"
	}
{{- end}}
	result, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return {{$.EntityName}}{}, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- if .EventType}}
	if r.bus != nil {
		r.bus.Emit(ctx, {{.EventAliasName}}{
			BaseEvent: events.NewBaseEvent("{{.EventType}}"),
			{{$.EntityName}}: result,
		})
	}
{{- end}}
	return result, nil
}
{{- else if eq .Category "scan_one_custom"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) ({{.ReturnTypeName}}, error) {
	result, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return {{.ReturnTypeName}}{}, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
	return result, nil
}
{{- else if eq .Category "scan_many"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) ([]{{$.EntityName}}, error) {
	results, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return nil, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
	return results, nil
}
{{- else if eq .Category "scan_one"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) ({{$.EntityName}}, error) {
	result, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return {{$.EntityName}}{}, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
	return result, nil
}
{{- else if eq .Category "update_returning"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) ({{$.EntityName}}, error) {
	result, err := r.store.{{.Name}}({{.CallArgs}})
	if err != nil {
		return {{$.EntityName}}{}, fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- if .EventType}}
	if r.bus != nil {
		r.bus.Emit(ctx, {{.EventAliasName}}{
			BaseEvent: events.NewBaseEvent("{{.EventType}}"),
			{{$.PKGoName}}: {{.EventPKExpr}},
			Update: input,
		})
	}
{{- end}}
	return result, nil
}
{{- else if eq .Category "update"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) error {
{{- if and .EventType .EventOutbox}}
	evt := {{.EventAliasName}}{
		BaseEvent: events.NewBaseEvent("{{.EventType}}"),
		{{$.PKGoName}}: {{.EventPKExpr}},
		Update: input,
	}
	payload, err := events.EncodeEvent(evt)
	if err != nil {
		return fmt.Errorf("{{.NameSpaced}}: encode outbox event: %w", err)
	}
	if err := r.store.{{.Name}}({{.CallArgs}}, events.OutboxEvent{
		Type:    "{{.EventType}}",
		Payload: payload,
	}); err != nil {
		return fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- else}}
	if err := r.store.{{.Name}}({{.CallArgs}}); err != nil {
		return fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- if .EventType}}
	if r.bus != nil {
		r.bus.Emit(ctx, {{.EventAliasName}}{
			BaseEvent: events.NewBaseEvent("{{.EventType}}"),
			{{$.PKGoName}}: {{.EventPKExpr}},
			Update: input,
		})
	}
{{- end}}
{{- end}}
	return nil
}
{{- else if eq .Category "exec"}}
// {{.Name}} delegates to the store.
func (r *Repository) {{.Name}}({{.Params}}) error {
{{- if and .EventType .EventOutbox}}
	evt := {{.EventAliasName}}{
		BaseEvent: events.NewBaseEvent("{{.EventType}}"),
		{{$.PKGoName}}: {{.EventPKExpr}},
{{- if .EventIsDelete}}
		Permanent: {{.EventPermanent}},
{{- end}}
	}
	payload, err := events.EncodeEvent(evt)
	if err != nil {
		return fmt.Errorf("{{.NameSpaced}}: encode outbox event: %w", err)
	}
	if err := r.store.{{.Name}}({{.CallArgs}}, events.OutboxEvent{
		Type:    "{{.EventType}}",
		Payload: payload,
	}); err != nil {
		return fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- else}}
	if err := r.store.{{.Name}}({{.CallArgs}}); err != nil {
		return fmt.Errorf("{{.NameSpaced}}: %w", err)
	}
{{- if .EventType}}
	if r.bus != nil {
		r.bus.Emit(ctx, {{.EventAliasName}}{
			BaseEvent: events.NewBaseEvent("{{.EventType}}"),
			{{$.PKGoName}}: {{.EventPKExpr}},
{{- if .EventIsDelete}}
			Permanent: {{.EventPermanent}},
{{- end}}
		})
	}
{{- end}}
{{- end}}
	return nil
}
{{- end}}
{{end}}
// Ensure imports are used.
var _ = time.Time{}
var _ = fop.Order{}
var _ context.Context
{{- if .HasEvents}}
var _ events.Event
{{- end}}
`

// =============================================================================
// Flat repository.go template — BOOTSTRAP (created once)
//
// Slimmed down: no embedding, no GeneratedStorer, just options and custom methods.
// =============================================================================

const repoRepositoryTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add custom repository methods, store methods, and configuration below.
//
// To customize a generated method: remove its @func from queries.sql,
// then define your version here.

package {{.PackageName}}

import (
	"context"

	"github.com/gopernicus/gopernicus/infrastructure/cryptids"
{{- if .HasEvents}}
	"github.com/gopernicus/gopernicus/infrastructure/events"
{{- end}}
	"github.com/gopernicus/gopernicus/sdk/fop"
)

// =============================================================================
// Storer
// =============================================================================

// Storer defines the {{.EntityNameLower}} data access contract.
// Add custom store methods above the markers. Generated methods between
// the markers are updated automatically by 'gopernicus generate'.
type Storer interface {
	// gopernicus:start (DO NOT EDIT between markers)
{{- range .Methods}}
	{{.Name}}({{.Params}}) {{.Returns}}
{{- end}}
	// gopernicus:end
}

// =============================================================================
// Repository
// =============================================================================

// Repository provides business logic for {{.EntityNamePlural}}.
type Repository struct {
	store      Storer
	generateID func() (string, error)
{{- if .HasEvents}}
	bus        events.Bus
{{- end}}
}

// Option configures a Repository.
type Option func(*Repository)

// WithGenerateID overrides the default ID generator (cryptids.GenerateID).
func WithGenerateID(fn func() (string, error)) Option {
	return func(r *Repository) { r.generateID = fn }
}
{{- if .HasEvents}}

// WithEventBus configures the event bus for emitting domain events.
func WithEventBus(bus events.Bus) Option {
	return func(r *Repository) { r.bus = bus }
}
{{- end}}

// NewRepository creates a new {{.EntityName}} repository.
func NewRepository(store Storer, opts ...Option) *Repository {
	r := &Repository{
		store:      store,
		generateID: cryptids.GenerateID,
	}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

// Ensure imports are used.
var _ context.Context
var _ fop.Order
`

// =============================================================================
// Flat fop.go template — BOOTSTRAP (created once)
//
// References OrderByFields directly (no GeneratedOrderByFields indirection).
// =============================================================================

const repoFopTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Customize ordering, defaults, and pagination here.

package {{.PackageName}}

import "github.com/gopernicus/gopernicus/sdk/fop"
{{if .HasList}}
// DefaultOrderBy is the default sort field for list operations.
const DefaultOrderBy = {{.DefaultOrderConst}}

// DefaultOrderDirection is the default sort direction for list operations.
const DefaultOrderDirection = {{.DefaultDirection}}

// DefaultLimit is the default page size for list operations.
const DefaultLimit = 25
{{- else}}
const DefaultOrderBy = OrderByPK
const DefaultOrderDirection = fop.ASC
const DefaultLimit = 25
{{- end}}

// Ensure fop import is used.
var _ = fop.ASC
`
