package generators

const specStoreGeneratedTemplate = `// Code generated by gopernicus. DO NOT EDIT.
// Regenerated on every 'gopernicus generate' run.
//
// Package {{.PackageName}} is the dialect-neutral store for the {{.RepoPkg}}
// entity: a declarative crud.Spec plus a Store embedding the generic
// crud.Store for the CRUD verbs. Hand-written methods live in store.go.

package {{.PackageName}}

import (
	"context"
	"errors"
{{- if .NeedsTime}}
	"time"
{{- end}}

	"{{.RepoImport}}"

	"{{.FrameworkPath}}/infrastructure/database/crud"
	"{{.FrameworkPath}}/sdk/errs"
)

// TxRunner executes fn inside a transaction, providing a tx-scoped querier.
// Wiring supplies it per driver (e.g. a pgx or database/sql transaction
// wrapped in the matching crud querier adapter).
type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error

// Spec is the declarative description of the {{.RepoPkg}} entity, derived
// from queries.sql and the reflected schema.
func Spec() crud.Spec{{.SpecTypeArgs}} {
	return crud.Spec{{.SpecTypeArgs}}{
		Table:   "{{.Table}}",
		PK:      "{{.PK}}",
		Columns: []string{ {{.ColumnsJoined}} },
{{- if .FilterFields}}
		Filters: func(f {{.FilterTypeExpr}}) []crud.Pred {
			var preds []crud.Pred
{{- range .FilterFields}}
			if f.{{.GoName}} != nil {
				preds = append(preds, crud.Pred{Col: "{{.Col}}", Op: crud.OpEq, Val: *f.{{.GoName}}})
			}
{{- if .IsTime}}
			if f.{{.GoName}}After != nil {
				preds = append(preds, crud.Pred{Col: "{{.Col}}", Op: crud.OpGT, Val: *f.{{.GoName}}After})
			}
			if f.{{.GoName}}Before != nil {
				preds = append(preds, crud.Pred{Col: "{{.Col}}", Op: crud.OpLT, Val: *f.{{.GoName}}Before})
			}
{{- end}}
{{- end}}
			return preds
		},
{{- end}}
{{- if .HasSearch}}
{{- if .Search.Column}}
		Search:     &crud.SearchSpec{Strategy: crud.{{.Search.StrategyConst}}, Column: "{{.Search.Column}}"},
{{- else}}
		Search:     &crud.SearchSpec{Strategy: crud.{{.Search.StrategyConst}}, Fields: []string{ {{.Search.FieldsJoined}} }},
{{- end}}
		SearchTerm: func(f {{.FilterTypeExpr}}) *string { return f.SearchTerm },
{{- end}}
{{- if .HasFilterStruct}}
		AuthorizedIDs: func(f {{.FilterTypeExpr}}) []string { return f.AuthorizedIDs },
{{- end}}
{{- if .CreateSets}}
		Creates: func(c {{.CreateTypeExpr}}) []crud.Set {
			return []crud.Set{
{{- range .CreateSets}}
				{Col: "{{.Col}}", Val: c.{{.GoName}}},
{{- end}}
			}
		},
{{- end}}
{{- if .UpdateFields}}
		Updates: func(u {{.UpdateTypeExpr}}) []crud.Set {
			var sets []crud.Set
{{- range .UpdateFields}}
			if u.{{.GoName}} != nil {
				sets = append(sets, crud.Set{Col: "{{.Col}}", Val: *u.{{.GoName}}})
			}
{{- end}}
			return sets
		},
{{- end}}
{{- if .HasUpdatedAt}}
		AutoNow: []string{"updated_at"},
{{- end}}
{{- if .AutoNowCreateJoined}}
		AutoNowCreate: []string{ {{.AutoNowCreateJoined}} },
{{- end}}
{{- if .RecordStateCol}}
		RecordStateCol: "{{.RecordStateCol}}",
{{- end}}
{{- if .OrderFields}}
		OrderFields: map[string]crud.OrderField{
{{- range .OrderFields}}
			"{{.Key}}": {Col: "{{.Col}}"{{if .CastLower}}, CastLower: true{{end}}},
{{- end}}
		},
		DefaultOrder: "{{.DefaultOrder}}",
{{- end}}
		MapError: func(err error) error {
			switch {
			case errors.Is(err, crud.ErrNotFound), errors.Is(err, errs.ErrNotFound):
				return {{.RepoPkg}}.Err{{.EntityName}}NotFound
			case errors.Is(err, errs.ErrAlreadyExists):
				return {{.RepoPkg}}.Err{{.EntityName}}AlreadyExists
			case errors.Is(err, errs.ErrInvalidReference):
				return {{.RepoPkg}}.Err{{.EntityName}}InvalidReference
			default:
				return err
			}
		},
	}
}

// Store satisfies {{.RepoPkg}}.Storer on any crud-supported database.
type Store struct {
	*crud.Store{{.SpecTypeArgs}}
	inTx TxRunner
}

var _ {{.RepoPkg}}.Storer = (*Store)(nil)

// NewStore builds the {{.RepoPkg}} store over a querier, dialect, and
// transaction runner for the same connection.
func NewStore(q crud.Querier, d crud.Dialect, inTx TxRunner) (*Store, error) {
	generic, err := crud.NewStore(q, d, Spec())
	if err != nil {
		return nil, err
	}
	return &Store{Store: generic, inTx: inTx}, nil
}
{{- range .RecordStateMethods}}

// {{.Name}} transitions the record state to "{{.State}}".
func (s *Store) {{.Name}}(ctx context.Context, {{.PKParam}} string) error {
	return s.SetRecordState(ctx, {{.PKParam}}, "{{.State}}")
}
{{- end}}
{{- range .CustomMethods}}
{{- if eq .Category "scan_one"}}

// {{.Name}} is a custom @func: literal SQL through the store's dialect and scanner.
func (s *Store) {{.Name}}({{.Params}}) ({{$.RepoPkg}}.{{$.EntityName}}, error) {
	args := crud.NewArgs(s.Dialect())
	query := {{.QueryExpr}}

	rows, err := s.Querier().Query(ctx, query, args.Values()...)
	if err != nil {
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapErr(err)
	}
	record, err := crud.ScanOne[{{$.RepoPkg}}.{{$.EntityName}}](rows, s.Dialect())
	if err != nil {
		return {{$.RepoPkg}}.{{$.EntityName}}{}, s.mapErr(err)
	}
	return record, nil
}
{{- else}}

// {{.Name}} is a custom @func (exec).
func (s *Store) {{.Name}}({{.Params}}) error {
	args := crud.NewArgs(s.Dialect())
	query := {{.QueryExpr}}

{{- if .SkipRowCheck}}

	if _, err := s.Querier().Exec(ctx, query, args.Values()...); err != nil {
		return s.mapErr(err)
	}
	return nil
{{- else}}

	affected, err := s.Querier().Exec(ctx, query, args.Values()...)
	if err != nil {
		return s.mapErr(err)
	}
	if affected == 0 {
		return {{$.RepoPkg}}.Err{{$.EntityName}}NotFound
	}
	return nil
{{- end}}
}
{{- end}}
{{- end}}
{{- if .UpdateKeyParams}}

// Update shadows the embedded single-key verb with this entity's composite
// key, delegating to the generic engine (UpdateBy maps errors via the Spec).
func (s *Store) Update(ctx context.Context, {{range .UpdateKeyParams}}{{.GoVar}} {{.GoType}}, {{end}}input {{.UpdateTypeExpr}}) ({{.RepoPkg}}.{{.EntityName}}, error) {
	return s.Store.UpdateBy(ctx, []crud.KeyVal{
{{- range .UpdateKeyParams}}
		{Col: "{{.Col}}", Val: {{.GoVar}}},
{{- end}}
	}, input)
}
{{- end}}
{{- if .HasCustom}}

func (s *Store) mapErr(err error) error {
	if err == nil {
		return nil
	}
	switch {
	case errors.Is(err, crud.ErrNotFound), errors.Is(err, errs.ErrNotFound):
		return {{.RepoPkg}}.Err{{.EntityName}}NotFound
	case errors.Is(err, errs.ErrAlreadyExists):
		return {{.RepoPkg}}.Err{{.EntityName}}AlreadyExists
	case errors.Is(err, errs.ErrInvalidReference):
		return {{.RepoPkg}}.Err{{.EntityName}}InvalidReference
	default:
		return err
	}
}
{{- end}}
{{- if .Skipped}}

// TODO: the following queries.sql funcs could not be translated by the spec
// generator — hand-write them in store.go (rung three of the escape ladder):
{{- range .Skipped}}
//   - {{.Name}}: {{.Reason}}
{{- end}}
{{- end}}
`

const specStoreBootstrapTemplate = `// This file is created once by gopernicus and will NOT be overwritten.
// Add hand-written store methods here — rung three of the crud escape
// ladder. Store and Spec are defined in generated.go; methods defined here
// are skipped by the generator on subsequent runs.
//
// The Store embeds *crud.Store, so hand-written methods can reach the
// execution surface directly: s.Querier() and s.Dialect() for literal SQL,
// crud.NewArgs(s.Dialect()) for positional argument accumulation, and
// crud.ScanOne / crud.ScanRows for entity scanning.
//
// TxRunner pattern: NewStore receives a TxRunner (defined in generated.go)
// that executes a function inside a transaction with a tx-scoped
// crud.Querier. Wiring supplies it per driver. A transactional method uses
// s.inTx and rebinds the spec'd verbs onto the transaction with
// s.WithQuerier(q):
//
//	func (s *Store) Create(ctx context.Context, input {{.RepoPkg}}.Create{{.EntityName}}) ({{.RepoPkg}}.{{.EntityName}}, error) {
//		var created {{.RepoPkg}}.{{.EntityName}}
//		err := s.inTx(ctx, func(q crud.Querier) error {
//			args := crud.NewArgs(s.Dialect())
//			sideEffect := "INSERT INTO ... VALUES (" + args.Add(input.{{.EntityName}}ID) + ")"
//			if _, err := q.Exec(ctx, sideEffect, args.Values()...); err != nil {
//				return err
//			}
//
//			record, err := s.WithQuerier(q).Create(ctx, input)
//			if err != nil {
//				return err
//			}
//			created = record
//			return nil
//		})
//		if err != nil {
//			return {{.RepoPkg}}.{{.EntityName}}{}, err
//		}
//		return created, nil
//	}

package {{.PackageName}}
`
