package generators

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gopernicus/gopernicus-cli/internal/schema"
)

// specStoreUsersQueries mirrors the framework's golden users entity
// (core/repositories/auth/users): a list with filters/search/order, the
// standard Get/Update/Delete verbs, record-state transitions, custom
// scan-one and exec funcs, and a Create handled by a hand-written
// transactional store method (deliberately absent from queries.sql).
const specStoreUsersQueries = `-- @database: primary

-- @func: List
-- @filter:conditions *
-- @search: ilike(email, display_name)
-- @order: *
-- @max: 100
SELECT *
FROM users
WHERE $conditions AND $search
ORDER BY $order
LIMIT $limit
;

-- @func: Get
SELECT *
FROM users
WHERE user_id = @user_id
;

-- @func: Update
-- @fields: *,-user_id,-record_state,-created_at
UPDATE users
SET $fields
WHERE user_id = @user_id
RETURNING *;

-- @func: SoftDelete
UPDATE users
SET record_state = 'deleted'
WHERE user_id = @user_id
;

-- @func: Archive
UPDATE users
SET record_state = 'archived'
WHERE user_id = @user_id
;

-- @func: Restore
UPDATE users
SET record_state = 'active'
WHERE user_id = @user_id
;

-- @func: Delete
DELETE FROM users
WHERE user_id = @user_id
;

-- @func: GetByEmail
SELECT *
FROM users
WHERE email = @email
;

-- @func: SetEmailVerified
-- @event: user.email_verified
UPDATE users
SET email_verified = true, updated_at = @updated_at
WHERE user_id = @user_id
;

-- @func: SetLastLogin
UPDATE users
SET last_login_at = @last_login_at, updated_at = @updated_at
WHERE user_id = @user_id
;
`

func specStoreUsersSchema() *schema.ReflectedSchema {
	cols := []schema.ColumnInfo{
		{Name: "user_id", DBType: "text", GoType: "string", IsPrimaryKey: true},
		{Name: "email", DBType: "text", GoType: "string"},
		{Name: "display_name", DBType: "text", GoType: "*string", IsNullable: true},
		{Name: "email_verified", DBType: "boolean", GoType: "bool"},
		{Name: "last_login_at", DBType: "timestamptz", GoType: "*time.Time", GoImport: "time", IsNullable: true},
		{Name: "record_state", DBType: "text", GoType: "string"},
		{Name: "created_at", DBType: "timestamptz", GoType: "time.Time", GoImport: "time"},
		{Name: "updated_at", DBType: "timestamptz", GoType: "time.Time", GoImport: "time"},
	}
	return &schema.ReflectedSchema{
		SchemaName: "public",
		Tables: map[string]*schema.TableInfo{
			"users": {
				TableName: "users",
				Schema:    "public",
				PrimaryKey: &schema.PrimaryKeyInfo{
					Column: "user_id",
					DBType: "text",
					GoType: "string",
				},
				Columns: cols,
			},
		},
	}
}

// normalizeSpaces collapses runs of spaces and tabs so fragment assertions
// are insensitive to gofmt's struct-literal alignment padding.
func normalizeSpaces(s string) string {
	var b strings.Builder
	space := false
	for _, r := range s {
		if r == ' ' || r == '\t' {
			space = true
			continue
		}
		if space && b.Len() > 0 && r != '\n' {
			b.WriteByte(' ')
		}
		space = false
		b.WriteRune(r)
	}
	return b.String()
}

func resolveSpecStoreUsers(t *testing.T) *ResolvedFile {
	t.Helper()
	qf, err := ParseString(specStoreUsersQueries)
	if err != nil {
		t.Fatalf("ParseString: %v", err)
	}
	qf.Table = "users"
	resolved, err := Resolve(qf, specStoreUsersSchema(), "auth")
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}
	return resolved
}

func renderSpecStoreUsers(t *testing.T) (generated, bootstrap string) {
	t.Helper()
	resolved := resolveSpecStoreUsers(t)

	data, err := BuildSpecStoreData(resolved, "github.com/example/app")
	if err != nil {
		t.Fatalf("BuildSpecStoreData: %v", err)
	}

	for name, tmpl := range map[string]string{
		"generated.go": specStoreGeneratedTemplate,
		"store.go":     specStoreBootstrapTemplate,
	} {
		out, err := renderSpecStoreTemplate(tmpl, data)
		if err != nil {
			t.Fatalf("render %s: %v", name, err)
		}
		formatted, err := format.Source(out)
		if err != nil {
			t.Fatalf("go/format %s: %v\n--- output ---\n%s", name, err, out)
		}
		switch name {
		case "generated.go":
			generated = string(formatted)
		case "store.go":
			bootstrap = string(formatted)
		}
	}
	return generated, bootstrap
}

func TestSpecStoreRender_Users(t *testing.T) {
	generated, bootstrap := renderSpecStoreUsers(t)

	wantGenerated := []string{
		// Header + package.
		"// Code generated by gopernicus. DO NOT EDIT.",
		"package usersstore",

		// Imports: framework paths from FrameworkPath, repo from ModulePath.
		`"github.com/example/app/core/repositories/auth/users"`,
		`"github.com/gopernicus/gopernicus/infrastructure/database/crud"`,
		`"github.com/gopernicus/gopernicus/sdk/errs"`,

		// TxRunner pattern.
		"type TxRunner func(ctx context.Context, fn func(crud.Querier) error) error",

		// Spec literal: generic type args, dialect-neutral table, columns.
		"func Spec() crud.Spec[users.User, users.FilterList, users.CreateUser, users.UpdateUser]",
		`Table:   "users"`,
		`"user_id", "email", "display_name", "email_verified", "last_login_at", "record_state", "created_at", "updated_at"`,

		// Filter predicates: eq plus gt/lt for time ranges.
		`crud.Pred{Col: "email", Op: crud.OpEq, Val: *f.Email}`,
		`if f.LastLoginAtAfter != nil`,
		`crud.Pred{Col: "last_login_at", Op: crud.OpGT, Val: *f.LastLoginAtAfter}`,
		`crud.Pred{Col: "created_at", Op: crud.OpLT, Val: *f.CreatedAtBefore}`,

		// Search: ilike → SearchContains across declared fields.
		"crud.SearchContains",
		`Fields: []string{"email", "display_name"}`,
		"SearchTerm: func(f users.FilterList) *string { return f.SearchTerm }",
		"AuthorizedIDs: func(f users.FilterList) []string { return f.AuthorizedIDs }",

		// Creates fallback (no insert query): all columns minus audit timestamps.
		`{Col: "user_id", Val: c.UserID}`,
		`{Col: "record_state", Val: c.RecordState}`,

		// Updates nil-check ladder from @fields.
		`crud.Set{Col: "display_name", Val: *u.DisplayName}`,
		`crud.Set{Col: "updated_at", Val: *u.UpdatedAt}`,

		// Auto timestamps + record state.
		`AutoNow: []string{"updated_at"}`,
		`AutoNowCreate: []string{"created_at", "updated_at"}`,
		`RecordStateCol: "record_state"`,

		// Order whitelist with CastLower on text columns, default order.
		`"email": {Col: "email", CastLower: true}`,
		`"user_id": {Col: "user_id"}`,
		`DefaultOrder: "created_at"`,

		// MapError against the sdk/errs sentinels.
		"case errors.Is(err, crud.ErrNotFound), errors.Is(err, errs.ErrNotFound):",
		"return users.ErrUserNotFound",
		"case errors.Is(err, errs.ErrAlreadyExists):",
		"return users.ErrUserAlreadyExists",
		"case errors.Is(err, errs.ErrInvalidReference):",
		"return users.ErrUserInvalidReference",

		// Store embedding + interface check + constructor.
		"*crud.Store[users.User, users.FilterList, users.CreateUser, users.UpdateUser]",
		"var _ users.Storer = (*Store)(nil)",
		"func NewStore(q crud.Querier, d crud.Dialect, inTx TxRunner) (*Store, error)",

		// Record-state wrappers.
		`return s.SetRecordState(ctx, userID, "deleted")`,
		`return s.SetRecordState(ctx, userID, "archived")`,
		`return s.SetRecordState(ctx, userID, "active")`,

		// Custom scan_one: literal SQL with star expansion, NewArgs + ScanOne.
		"func (s *Store) GetByEmail(ctx context.Context, email string) (users.User, error)",
		"args := crud.NewArgs(s.Dialect())",
		`"SELECT user_id, email, display_name, email_verified, last_login_at, record_state, created_at, updated_at FROM users WHERE email = " + args.Add(email)`,
		"crud.ScanOne[users.User](rows, s.Dialect())",

		// Custom exec: time args through the dialect, affected-rows check.
		"func (s *Store) SetEmailVerified(ctx context.Context, updatedAt time.Time, userID string) error",
		`"UPDATE users SET email_verified = true, updated_at = " + args.Add(s.Dialect().TimeArg(updatedAt)) + " WHERE user_id = " + args.Add(userID)`,
		"func (s *Store) SetLastLogin(ctx context.Context, lastLoginAt time.Time, updatedAt time.Time, userID string) error",
		"args.Add(s.Dialect().TimeArg(lastLoginAt))",
		"if affected == 0 {",
	}
	normalized := normalizeSpaces(generated)
	for _, want := range wantGenerated {
		if !strings.Contains(normalized, normalizeSpaces(want)) {
			t.Errorf("generated.go missing fragment:\n%s", want)
		}
	}

	// Standard verbs come from the embedded generic store — they must not be
	// regenerated as methods.
	for _, banned := range []string{
		"func (s *Store) List(",
		"func (s *Store) Get(",
		"func (s *Store) Create(",
		"func (s *Store) Update(",
		"func (s *Store) Delete(",
		// No schema-qualified identifiers in dialect-neutral SQL.
		"public.users",
	} {
		if strings.Contains(generated, banned) {
			t.Errorf("generated.go must not contain %q", banned)
		}
	}

	// Bootstrap: created-once header, package, TxRunner pattern docs.
	for _, want := range []string{
		"will NOT be overwritten",
		"package usersstore",
		"TxRunner pattern",
		"s.WithQuerier(q)",
	} {
		if !strings.Contains(bootstrap, want) {
			t.Errorf("store.go missing fragment:\n%s", want)
		}
	}

	if t.Failed() {
		t.Logf("generated.go:\n%s", generated)
	}
}

// TestSpecStoreRender_SkippedFuncs verifies that funcs the translator cannot
// confidently handle become TODO comments instead of broken code.
func TestSpecStoreRender_SkippedFuncs(t *testing.T) {
	queries := `-- @database: primary

-- @func: Get
SELECT *
FROM users
WHERE user_id = @user_id
;

-- @func: CountByState
SELECT record_state, count(*) AS total
FROM users
GROUP BY record_state
;

-- @func: PromoteAll
WITH ranked AS (SELECT user_id FROM users)
UPDATE users SET record_state = 'active'
WHERE user_id IN (SELECT user_id FROM ranked)
;
`
	qf, err := ParseString(queries)
	if err != nil {
		t.Fatalf("ParseString: %v", err)
	}
	qf.Table = "users"
	resolved, err := Resolve(qf, specStoreUsersSchema(), "auth")
	if err != nil {
		t.Fatalf("Resolve: %v", err)
	}

	data, err := BuildSpecStoreData(resolved, "github.com/example/app")
	if err != nil {
		t.Fatalf("BuildSpecStoreData: %v", err)
	}

	out, err := renderSpecStoreTemplate(specStoreGeneratedTemplate, data)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	formatted, err := format.Source(out)
	if err != nil {
		t.Fatalf("go/format: %v\n--- output ---\n%s", err, out)
	}
	generated := string(formatted)

	for _, want := range []string{
		"// TODO: the following queries.sql funcs could not be translated",
		"//   - CountByState:",
		"//   - PromoteAll:",
	} {
		if !strings.Contains(generated, want) {
			t.Errorf("generated.go missing fragment:\n%s\n--- output ---\n%s", want, generated)
		}
	}
	for _, banned := range []string{
		"func (s *Store) CountByState(",
		"func (s *Store) PromoteAll(",
	} {
		if strings.Contains(generated, banned) {
			t.Errorf("generated.go must not contain %q", banned)
		}
	}
}

// TestGenerateSpecStore_BootstrapDiscipline runs the full generator twice
// against a temp dir: store.go is created once and preserved, generated.go is
// always rewritten, and methods customized in store.go are skipped.
func TestGenerateSpecStore_BootstrapDiscipline(t *testing.T) {
	resolved := resolveSpecStoreUsers(t)
	repoDir := t.TempDir()

	if err := GenerateSpecStore(resolved, repoDir, "github.com/example/app", Options{}); err != nil {
		t.Fatalf("GenerateSpecStore: %v", err)
	}

	storeDir := filepath.Join(repoDir, "usersstore")
	genPath := filepath.Join(storeDir, "generated.go")
	bootPath := filepath.Join(storeDir, "store.go")

	firstGen, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read generated.go: %v", err)
	}
	if !strings.Contains(string(firstGen), "func (s *Store) GetByEmail(") {
		t.Fatalf("generated.go missing GetByEmail on first run")
	}

	// Customize the bootstrap: hand-write GetByEmail.
	custom := `package usersstore

import (
	"context"

	"github.com/example/app/core/repositories/auth/users"
)

// GetByEmail is customized — the generator must skip it.
func (s *Store) GetByEmail(ctx context.Context, email string) (users.User, error) {
	return users.User{}, nil
}
`
	if err := os.WriteFile(bootPath, []byte(custom), 0644); err != nil {
		t.Fatalf("write custom store.go: %v", err)
	}

	if err := GenerateSpecStore(resolved, repoDir, "github.com/example/app", Options{}); err != nil {
		t.Fatalf("GenerateSpecStore (second run): %v", err)
	}

	secondGen, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatalf("read generated.go: %v", err)
	}
	if strings.Contains(string(secondGen), "func (s *Store) GetByEmail(") {
		t.Errorf("generated.go still contains GetByEmail after customization in store.go")
	}
	if !strings.Contains(string(secondGen), "func (s *Store) SetLastLogin(") {
		t.Errorf("generated.go lost SetLastLogin on second run")
	}

	bootAfter, err := os.ReadFile(bootPath)
	if err != nil {
		t.Fatalf("read store.go: %v", err)
	}
	if string(bootAfter) != custom {
		t.Errorf("bootstrap store.go was overwritten on regeneration")
	}
}
